### ISSUE TITLE
Buflist : make indenting of numbers optional

### ISSUE THREAD

**Issue by troudbal** [weechat/weechat#1030]
When using the buflist bar in top or bottom position, the indenting of buffer numbers can be very annoying. It should be optional or enabled only if the buflist bar is left/right positioned.

**Comment by flashcode** [comment]
Hi,
The indenting of number is already optional, you can just replace `${number}` by `${buffer.number}` in the option `buflist.format.number`.

**Comment by flashcode** [comment]
By design, it's not really possible to know where the bar item is displayed, when building its content (it's done automatically by WeeChat when displaying it).
The script buffers.pl does that by reading the value of option `weechat.bar.buffers.position` but this is a hack and works only if the item is in this bar; so not a good solution for me.
The most important is that you can disable the indenting if you don't need it.

**Comment by troudbal** [comment]
Using `${buffer.number}` is OK, thanks.
