### ISSUE TITLE
Split weechat-plugins debian package into several packages (one per scripting language)

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#1085]
Currently, the `weechat-plugins` package contains the following plugins (sorted alphabetically):

- aspell
- exec
- fifo
- guile
- javascript
- lua
- perl
- php
- python
- relay
- ruby
- script
- tcl
- trigger

The purpose of this issue is to split this `weechat-plugins` package into 9 packages: one package per scripting language supported, and still the `weechat-plugins` with the other plugins.

So the packages will become:

- weechat-plugins:
  - aspell
  - exec
  - fifo
  - relay
  - script
  - trigger
- weechat-guile
- weechat-javascript
- weechat-lua
- weechat-perl
- weechat-php
- weechat-python
- weechat-ruby
- weechat-tcl

With these packages, it is easier to install only some languages, and the package `weechat-plugins` does not require to install all the interpreters any more.

**Comment by sim642** [comment]
I haven't tried this myself (probably should) but it's a concern I've brought up before regarding such splitting of packages: upgrading from 1.9 to 2.0 breaks all script plugins and scripts because `weechat-plugins` package will be upgraded but it will not contain script plugins anymore and the upgrade process will not install any of the separate plugins. This very much breaking change can be documented as much as we want but the obvious truth is that most people will not go find and read WeeChat release notes when they upgrade packages through their package manager (e.g. `apt upgrade`) to know about it and instead will come to `#weechat` to ask about it again and again.

I'm wondering if there wouldn't be a better way to do the splitting which wouldn't cause such vast breakage, e.g. have a separate package `weechat-core` (or something), which contains `aspell`, `exec`, etc, and make `weechat-plugins` a metapackage that just depends on `weechat-core`, `weechat-guile`, etc. This way anyone upgrading will still get all the script plugins as they had before but they would simply get split across multiple packages. Anyone doing a new install could just install `weechat-core` and the desired script plugins, not everything. Anyone who has upgraded could also install `weechat-core` and remove the metapackage and unneeded script plugins.

I'm wondering what are everyone's thoughts about causing things to break big time.

**Comment by iam-TJ** [comment]
This should be covered by the debian/.postinst scripts. That's what they're for. Also in debian/control declaring "Breaks:"
