### ISSUE TITLE
Ignores compose key

### ISSUE THREAD

**Issue by victor-catalyst** [weechat/weechat#1097]
How to reproduce:

1. Map <kbd>Caps Lock</kbd> as the compose key using for example `setxkbmap -layout us -variant dvorak-alt-intl -option compose:caps`.
1. Start WeeChat 1.9.1 in XTerm 322.
1. Press <kbd>Caps Lock</kbd> followed by <kbd>aa</kbd>.

Expected behaviour: It should print "å".

Actual behaviour: It prints "aa".

**Comment by Mikaela** [comment]
I cannot reproduce this with `compose:menu`.

**Comment by victor-catalyst** [comment]
@Mikaela Did you try with <kbd>Caps Lock</kbd>?

**Comment by Mikaela** [comment]
@victor-catalyst When I wrote the comment I didn't, I communicated unclearly and tried to point out that the issue title is invalid.

However now that I asked, I tried and `Caps Lock` as `compose` key works without issues\*, so I cannot reproduce this.

From [required info of Contributing.adoc](https://github.com/weechat/weechat/blob/master/Contributing.adoc#required-info):

* WeeChat version:
    * WeeChat 1.9.1 [compiled on Sep 23 2017 19:44:10]
    * WeeChat 2.0-dev (git: v1.9-416-g093af02) [compiled on Oct 30 2017 14:16:21]
* `lsb_release -sa`
    * 1.4 Arch "Arch Linux" rolling n/a   
    * No LSB modules are available. | Debian | Debian GNU/Linux 8.9 (jessie) | 8.9 | jessie

I am running the toppernmost details are from my localhost (rxvt-unicode (urxvt) v9.22 - released: 2016-01-23) in tmux 2.6 and the lower is over ssh in tmux 1.9.

* * * * *

\* *to be honest I did encounter irrelevant issues such as copy-pasting `setxkbmap -layout us -variant dvorak-alt-intl -option compose:caps` to my terminal without sanity checking it first as I am using Finnish/Swedish QWERTY keyboard and it took me a moment to restore back from US Dvorak and after adjusting my own command I accidentally first wrote `capslock` instead of `caps` which naturally didn't work and when I reached the correct command (`setxkbmap -option compose:caps -option terminate:ctrl_alt_bksp -option nbsp:none`) I had locked my laptop to only use Caps Lock which again took a little of searxing to find [these instructions for disabling Caps Lock from terminal](https://askubuntu.com/a/607915) where finally `sudo pacman -S xdotool && xdotool key Caps_Lock` finally let me out of CAPS LOCKED state. I think `Caps Lock` as `Compose` is a nice idea and I might be copying you later, have you encountered any drawbacks that way?*

**Comment by victor-catalyst** [comment]
I don't know what else to do then, because it works in at least Firefox, Thunderbird, XTerm+Bash. Interestingly, I tested with two applications where I have never needed the compose key, JetBrains IDEA and Git GUI, and it fails in both of them as well. So this is actually a wider issue. My bad.
