### ISSUE TITLE
hotlist_changed signal should provide data of the buffer added to hotlist

### ISSUE THREAD

**Issue by dkess** [weechat/weechat#1133]
Right now the `hotlist_changed` signal provides no data. However it would be useful for scripts to have access to the buffer that was changed, and what notify level was used.

**Comment by flashcode** [comment]
Hi,
After looking at the code it seems a bit harder than I thought to implement that, because the signal can be sent for multiple reasons:
* a new buffer added to the hotlist
* a buffer already in the hotlist is changed with a higher priority (for example message --> highlight)
* the hotlist is cleared completely
* the hotlist is cleard for a given level
So for the two last changes, it's not possible to give a buffer. One solution for this problem would be to send nothing (as it's done currently) in case you clear (completely or partially) the hotlist. And send the buffer info only when it's relevant (buffer added or changed).
