### ISSUE TITLE
Python 3 API: UnicodeDecodeError when key_pressed is called for mouse events

### ISSUE THREAD

**Issue by GermainZ** [weechat/weechat#1220]
## Bug summary

Python 3 scripts crash when catching mouse events (and possibly other keycodes that aren't utf8) using e.g. the key_pressed hook.

## Current behavior

    python: stdout/stderr (test): UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte
    python: error in function "cb_key_pressed"

## Steps to reproduce

1. Compile WeeChat with python3 support.
2. Install and load the minimal script to reproduce the bug below.
3. Enable mouse mode (meta-m) in WeeChat.
4. Click anywhere.

## Script to reproduce the bug

```
import weechat

SCRIPT_NAME = "1220"
SCRIPT_AUTHOR = "GermainZ <germanosz@gmail.com>"
SCRIPT_VERSION = "0.1"
SCRIPT_LICENSE = "WTFPL"
SCRIPT_DESC = ("Sample script to reproduce the UnicodeDecodeError issue")

def cb_key_pressed(data, signal, signal_data):
    return weechat.WEECHAT_RC_OK

weechat.register(SCRIPT_NAME, SCRIPT_AUTHOR, SCRIPT_VERSION, 
                 SCRIPT_LICENSE, SCRIPT_DESC, "", "")
weechat.hook_signal("key_pressed", "cb_key_pressed", "")
```

---

- WeeChat version: WeeChat 2.2-rc1 (git: v2.2-rc1-5-g3d0e26ce3)
- WeeChat Python version: 3.6.6
- OS, distribution and version: Linux / Arch Linux

**Comment by sim642** [comment]
### Investigation
Weechat uses [`PyObject_CallFunction`](https://docs.python.org/3/c-api/object.html#c.PyObject_CallFunction) to call the signal callback function. Its documented to use [`Py_BuildValue`](https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue), which does the following in Python3 with the "s" format being used here:
> Convert a null-terminated C string to a Python str object using **'utf-8'** encoding. If the C string pointer is NULL, None is used.

On the contrary, Python2 doesn't do any decoding for string arguments by default and is documented as:
> Convert a null-terminated C string to a Python object. If the C string pointer is NULL, None is used.

### Thoughts
While in most cases signal data and other data passed back to scripts will be just text and thus UTF-8, it's not necessarily so as this case with mouse events via `key_pressed` demonstrates. Some signals and other aspects of the API deal with possibly non-UTF-8 data, which in C is all represented with `char*` and thus uniformly handled by Python. In cases like `key_pressed` it would make more sense for this data to be given to scripts as bytes instead of str which would avoid this implicit encoding step.

There are other situations where non-UTF-8 data is being handled (e.g. IRC formatting codes, Weechat color codes) where it could be similarly problematic with Python3. It may be just by chance that all of such data happens to be also valid UTF-8 but mouse events in `key_pressed` apparently don't and it's not obvious if anything else could be affected.

### Solutions
1. Add extra information to Weechat Python API implementation to note whether some data should be str or bytes and thus which format character to use for the same `char*` argument. Then make `key_pressed` etc pass it as bytes instead to avoid the problem.
2. Add custom trickery when passing `char*` to Python like "if it's UTF-8 then pass as str, otherwise as bytes". This would be more of a sledgehammer solution that avoids dealing with the actual deeper problem that we face here. Also it might be weird for Python3 scripts as the same callback may receive str/bytes arguments depending on the situation.
3. Flat out pass all `char*` data to Python3 as bytes. This completely avoids the problem and in a way is more consistent with the Python2 implementation which uses str (aka bytes in Python3) and not unicode (aka str in Python3). Python2 scripts currently need to do `.decode('utf-8')` by hand when dealing with unicode strings and not under Python3 where this currently is implicit. While it would be most consistent, it's also the most destructive approach: existing Python3 scripts are likely to break and they'd be stuck with having to still deal with bytes and manually decoding them, which isn't nice.
4. Your better suggestion...


**I consider this issue extremely important in terms of our ongoing Python3 adoption because it makes certain operations impossible to do in Python3 due to errors coming from within the API implementation and possible solutions have different negative effects on API usability.**

**Comment by sim642** [comment]
After some more clicking around it seems that the error only happens with clicks/mouse scrolls with high enough coordinates to cause some byte to be at least `0x80` to cause invalid UTF-8. So click on the right side of the terminal, not in the top left corner to consistently reproduce.

**Comment by flashcode** [comment]
I think everything passed as "string" to the scripting API should be UTF-8 valid.
And I think the mouse codes is the only one string (I hope) that can be invalid UTF-8. So maybe this specific signal could be fixed and made UTF-8 valid.

By this way, this problem could be related to some terminals only, I know that rxvt-unicode for example will send UTF-8 valid data as mouse codes, which is not the case for all terminals.
