### ISSUE TITLE
Cannot use "/buffer network.#channel" in weechat.startup.command_{before,after}_plugins

### ISSUE THREAD

**Issue by ChaiTRex** [weechat/weechat#1232]
## Bug summary

Cannot use `"/buffer network.#channel"` in `weechat.startup.command_{before,after}_plugins`
## Current behavior

I used the following commands to try to switch to a particular channel's buffer right when WeeChat 2.2 starts:

    /set irc.look.buffer_switch_autojoin off
    /set weechat.startup.command_before_plugins "/buffer network.#channel"
    /set weechat.startup.command_after_plugins "/buffer network.#channel"
    /save

I get error messages in the `weechat` buffer saying that I should read `/help buffer`, though that seems incorrect since `/buffer network.#channel` works normally and `/help buffer` even mentions it.

It's also frustrating that I have to use `irc.server.network.command` instead, since that delays the switching to the desired channel's buffer for a while rather than doing it immediately on startup. It also causes an unwanted switch to the channel when reconnecting to the server (I only want to switch to it on WeeChat startup, not on every reconnection).

## Steps to reproduce

1. Run the four commands above
2. Exit WeeChat
3. Start WeeChat
4. Note that the channel's buffer isn't selected
5. Note that there are error messages in the `weechat` buffer

## Desired behavior

It would be nice if this worked, since the channel's buffer already exists and is properly named in the UI when the program opens.

## Suggested solutions

None

## Additional information

`irc.look.buffer_open_before_autojoin` is set to `on`. I also have `irc.look.server_buffer` set to `independent` if that matters.

---

- WeeChat version: 2.2
- OS, distribution and version: Ubuntu 16.04.5 LTS

**Comment by flashcode** [comment]
Hi,

This is because the buffer you are trying to switch to is not yet created (buffers are opened asynchronously by irc plugin, so when the plugin is just loaded, they're not yet opened).
I could mute the `/buffer xxx` command when the buffer is not found, but not sure if that's the desired behavior: this could mute an error if the `/buffer` argument is not a buffer name but is invalid.
Instead you could fix the way to switch to buffers, for example by adding a delay:

    /set weechat.startup.command_after_plugins "/wait 2 /buffer network.#channel"

Or you can still mute the command yourself, but this will not solve the switch to the buffer: `/mute /buffer network.#channel`

**Comment by ChaiTRex** [comment]
Thank you. Adding that delay fixed the problem.
