### ISSUE TITLE
Weechat crashed (SIGSEGV) on /upgrade

### ISSUE THREAD

**Issue by daurnimator** [weechat/weechat#1276]
Possible dupe of https://github.com/weechat/weechat/issues/1217 ?

## Bug summary

Weechat crashed (SIGSEGV) on `/upgrade`

## Current behavior

```
*** Very bad! WeeChat is crashing (SIGSEGV received)                                             
*** Full crash dump was saved to /home/daurnimator/.weechat/weechat_crash_20181028_601.log file.
***
*** Please help WeeChat developers to fix this bug:
***   1. If you have a core file, please run:  gdb /path/to/weechat core
***      then issue command: "bt full" and send result to developers
***      (see user's guide for more info about report of crashes).
***   2. Otherwise send backtrace (below), only if it is a complete trace.
***      Keep the crash log file, just in case developers ask you some info
***      (be careful, private info like passwords may be in this file).

======= WeeChat backtrace =======
(written by WeeChat 2.2, compiled on Aug  1 2018 12:25:48)
001  ??:? [function weechat_backtrace]
002  ??:? [function debug_sigsegv]
003  sigaction.c:? [function __restore_rt]
004  ??:? [function gui_color_get_name]
005  ??:? [function relay_buffer_refresh]
006  ??:? [function relay_client_send]
007  ??:? [function relay_weechat_msg_send]
008  ??:? [function relay_weechat_protocol_signal_buffer_cb]
009  ??:? [function hook_signal_send]
010  ??:? [function gui_buffer_visited_remove_by_buffer]
011  ??:? [function plugin_remove]
012  ??:? [function plugin_unload]
013  ??:? [function plugin_unload_all]
014  ??:? [function plugin_end]
015  ??:? [function command_upgrade]
016  ??:? [function hook_command_exec]
017  ??:? [function input_exec_command]
018  ??:? [function input_data]
019  ??:? [function gui_input_return]
020  ??:? [function command_input]
021  ??:? [function hook_command_exec]
022  ??:? [function input_exec_command]
023  ??:? [function input_data]
024  ??:? [function gui_key_pressed]
025  ??:? [function gui_key_flush]
026  ??:? [function gui_key_read_cb]
027  ??:? [function hook_fd_exec]
028  ??:? [function gui_main_loop]
029  ??:? [function main]
030  ??:? [function __libc_start_main]
031  ??:? [function _start]
======= End of  backtrace =======
Aborted (core dumped)
```

---

- WeeChat version: 2.2
- OS, distribution and version: Arch

**Comment by weechatter** [comment]
If its a on-off happening, very difficult to trace down.

At least a "bt full" would be helpfull. remove all sensitive data and send it to developer with nextcloud or a simliar service.

**Comment by daurnimator** [comment]
Closing as haven't been able to replicate.

**Comment by ArchI3Chris** [comment]
Seems this was closed. But I do have the same problem now. I did use Arch Linux and WeeChat since this one has been opened until this day. I didn't have the problem before. At least not that I know of. I don't use WeeChat every day. But every now and then and never had any problems so far. Even on multiple devices (same setup though).

But now I do have this problem. Too with WeeChat. Too on Arch Linux. Too SigSegv. Yes, WeeChat does run with -s and without scripts. So, it looks like a problem with scripts at first glance. BUT... the scripts didn't change. In fact, I've set this up years ago and it has been working since. I've never touched it since. I don't even know, what kind of scripts I have in there. Also, I don't se an option to actually find out, which one causes the problem or where in the particular script the problem is being caused.

But the truth is, since I ran an upgrade today, it is far more likely that WeeChat got upgraded and the problem is not in the scripts, but actually in the implementation and use of the same by WeeChat. Because there was not a single character change in any configuration and setup. I didn't even as much as touch it. I didn't even look at it. Not even the directory. This setup has been working for years. Now after an upgrade it doesn't. So, this is not a problem with scripts. This is a problem with the impementation and how the scripts are being used by WeeChat!
