### ISSUE TITLE
Support option types for `config_set_plugin`

### ISSUE THREAD

**Issue by squigglezworth** [weechat/weechat#1379]
Pretty straight-forward - Add another argument to the `config_set_plugin` API function so we can specify the option type, and take advantage of things like fset's keybinds that work on different option types (toggle, increment/decrement)

**Comment by squigglezworth** [comment]
To expand on this: It would also be ideal to handle all the other option variables, such as min/max, description, etc

**Comment by flashcode** [comment]
Hi,

Supporting types and other options (min/max) for `config_set_plugin` is not scheduled, because you can already do that with your own config file (some scripts already use their own config to have full control on their options, for example: https://weechat.org/scripts/source/otr.py.html/).

The function `config_set_plugin` is just a quick way to define options in scripts, and is by design limited to string options without the other features (the only thing available is a description of the option).

**Comment by squigglezworth** [comment]
>  and is by design limited to string options without the other features (the only thing available is a description of the option).

Why, though? As you say, the point of that function is to provide a quick and easy way of setting options - why not expand on that ease instead of supporting only the bare minimum for options? I'd even argue that it's hardly the bare minimum, since forcing every option to be a string doesn't successfully convey meaning, especially when scripts don't have option descriptions (even when they do, it's not always clear what values an option will accept)


And I understand that we can add a new config file, but this seems like overkill for most scripts. A script with 3 options doesn't really need its own config section, and having only some script options outside of the normal script namespace seems confusing.
