### ISSUE TITLE
Add support for cap echo-message

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#139]
Via https://github.com/znc/znc/pull/603 .

http://ircv3.net/specs/extensions/echo-message-3.2.html

If I understand correctly, this only makes server/bouncer send messages that are send from WeeChat back to WeeChat.

There is ZNC module http://wiki.znc.in/Privmsg which does this always and I have used it for months with WeeChat without any issues, so I think that WeeChat already supports this as long as WeeChat requests it from server.

Update: self-message was deprecated by echo-message.

**Comment by Mikaela** [comment]
Did anyone ever do testing for echo-message? It seems that I forgot to comment long time ago about IRCv3 deprecating self-message in favour of echo-message.

**Comment by Mikaela** [comment]
Quick test: it duplicates all messages you send.

**Comment by BlacklightShining** [comment]
@Mikaela It doesn't _duplicate_ them, per se; it causes the server to echo them back. This is desirable as it gives clients (and users!) confirmation that a message has been received by the network and is being relayed to other users (at the expense of some bandwidth, sure, but I really can't see that being an issue in this day and age). It can also be used to test lag to the network without the use of extra `PING`s.

Personally, I would like very much to see weechat implement this capability (along with visibly marking uncomfirmed messages, using each sent message to check lag, and deferring logging for each message until confirmation is received).

**Comment by Mikaela** [comment]
How Communi Sailfish does this is:

1. You send a message.
2. Server echoes the message.
3. The sent message appears in the buffer.

So the sent message is not shown at all until step 3. This is probably the easiest way to implement it, but it could be nicer such as having balls in front of user's own messages:

* Green - message delivered
* Yellow - message pending (waiting for echo)
* Red - message sending failed (better to integrate with yellow or in case there is disconnect or something?)

Echo-message is important to have so the alls can be implemented later if at all. At least two widely encountered cases have been encountered:

* If client supports server-time, but not echo-message and the client clock is on wrong time, the timestamps become inconsistent. With echo-message supported the time message was sent would be taken from server-time. (https://github.com/znc/znc/issues/1144)
* Receiving own messages from queriy playback when using a bouncer such as ZNC.

**Comment by BlacklightShining** [comment]
@Mikaela I dunno about “balls”, for weechat. That sounds more like something you'd see in a GUI client. I could definitely see red|yellow asterisks in the prefix column or something (though I'd personally prefer no asterisk over a green asterisk, or maybe a green asterisk that disappears after a couple seconds). Each sent message might also be shown in a single color (dark gray?) until confirmation is received—[Stack Exchange's chat](https://chat.stackexchange.com/) does this.

**Comment by Mikaela** [comment]
UTF-8 exists and WeeChat uses it internally, so balls `○` are possible. There could even be `☺` and `☹` :stuck_out_tongue_winking_eye: 

Asterisks would also be nice and I like the disappearing asterisk suggestion, but it should probably be supported first without it to avoid too much work. Disappearing and then appearing messages might also work better with server-time and avoid https://github.com/znc/znc/issues/1144 / https://github.com/ircv3/ircv3-specifications/issues/182.

**Comment by BlacklightShining** [comment]
You could always make the specific character|string and its colors configurable. :)

**Comment by sim642** [comment]
All these ideas about a message's sending status indicator are great except "echo-message" is inherently broken in that sense: the server must echo your message as it is sent to any other client, i.e. with all the modifications it has applied to it (color stripping, censoring, whatnot). This means that it's impossible for a client to tell, which echoed message corresponds to which sent line.

**Comment by BlacklightShining** [comment]
@sim642 You're completely right…I mean, it totally makes sense for `echo-message` to behave that way (else, clients and users couldn't tell if their messages were modified, and they what they saw might differ from what everyone else saw), but since IRC doesn't tag messages like e.g. IMAP does, a client can't necessarily match up a sent message to its echo. Augh!

As a workaround…let's see. If this were just implemented as it is, then when we sent a message that was modified, the version we sent would appear with an _unconfirmed_ indicator, and then the echoed version would appear below it. What we could do is take note when a sent message has gone unconfirmed, but anything sent _after_ it _was._ (And maybe also `PING` with a random token after a few seconds or something, to make that happen faster.) If that happens, then we can just remove the unconfirmed copy from the display: because IRC lines are always processed in order (right?), it must have either a modified echo or an error that's already onscreen.

**Comment by DarthGandalf** [comment]
There is a proposal to add such tags to messages: https://github.com/ircv3/ircv3-specifications/pull/162
I need to find some time to address the comments in it...

**Comment by sim642** [comment]
@BlacklightShining There's the problem that behind a bouncer, another client of the bouncer could send lines and receive `echo-message` replies which match up to none of the lines sent from the other clients. This would completely mess up the matching, which lines have been processed and which not.

The best that could be done right now is simply not displaying lines locally but waiting for the echoed replies to come back. Without message labeling the status indicator can not reliably be implemented and a partially working solution shouldn't be put in either.

**Comment by Mikaela** [comment]
> The best that could be done right now is simply not displaying lines locally but waiting for the echoed replies to come back.

This would be the best for now in my opinion. At IRC you talked about it giving impression of laggy client, but it's better than nothing and if users don't like it, they can disable it.

**Comment by DarthGandalf** [comment]
> if users don't like it, they can disable it

Or they can understand that the client is laggy, and switch to another client without way to know that this "feature" can be disabled in settings.

**Comment by sim642** [comment]
It's not really that way around though. By default no capabilities are enabled anyway, so `echo-message` wouldn't be either, allowing current local echoing behavior to work as it always has. It should be said that `echo-message` can be enabled explicitly if the user actually wants it like that.

**Comment by BlacklightShining** [comment]
@DarthGandalf `labeled-replies` would help _immensely_ here, but I feel like we need a workaround in the meantime…and for all those servers that will never get it, of course.

@sim642 Bouncers are subject to the same strict line ordering as everything else, yeah? Couldn't a client to a bouncer apply the same algorithm, but using only messages that _it specifically_ sent (as opposed to another client to the same bouncer)?

@DarthGandalf So, by default, either use the current behavior; or use the colored asterisks (or whatever) when `labeled-replies` is available, and fall back to the current behavior when it's not. I'm not super concerned with it being a certain way _by default;_ I just want it to be an _option._

**Comment by sim642** [comment]
@BlacklightShining Even when you assume that bouncers always keep the order of messages that doesn't get us any closer. If two clients send a line and both lines get an echo (so both clients receive two echoes), there's no way for either client to know which echo was for its sent line.

**Comment by BlacklightShining** [comment]
@sim642 Oh, do you mean that the lines are _identical?_ That could cause a problem, yeah…

**Comment by sim642** [comment]
@BlacklightShining Not even identical. The echoed reply could (and in numerous cases *should*) be different than the one the client sent, so there's no guaranteed way to match up echoed lines to sent ones.

**Comment by BlacklightShining** [comment]
@sim642 Well, we [already know](https://github.com/weechat/weechat/issues/139#issuecomment-167319948) there's an issue when messages are modified server-side. We'll just have to make those `PING` tokens sufficiently long and random that the possibility that two clients to the same bouncer will come up with the same one at around the same time negligible.

**Comment by sim642** [comment]
@BlacklightShining Since the solution you described is probabilistic, i.e. not guaranteed to always correctly work, I consider it more of a workaround than a solution (because message labels are the solution for this). For this reason I think such solution should not be implemented and I think @flashcode would agree on this with me.

If you really wanted such status indication without having message labels, implement it in a script but not WeeChat itself because having a system which is known to be prone to incorrect behavior should not be in the core.

**Comment by BlacklightShining** [comment]
@sim642 So core might get status indications for just `labeled-replies` networks? That's cool.

**Comment by louiz** [comment]
> The best that could be done right now is simply not displaying lines locally but waiting for the echoed replies to come back.

I think this is actually the correct way to do it (not just “right now”, but at all time).

For your information, that’s how XMPP clients do it. And it has numerous advantages over the old-school IRC way:

- If you send a message while banned, your message doesn’t wrongly appear on your buffer as if it was actually sent to all occupants of the channel: when your message is filtered, nobody sees it not even you.
- If your message is being modified by the server (words are censored, or color stripped for example), you know how everyone sees them.
- Since all messages are always echoed by the server, you know the order in which the conversation is being seen by everyone. If you receive your own message after someone else’s message, you know that this is the same order for everyone in the channel (for IRC, this would be true only for everyone who activated the echo-message capacity)

I’ve only heard the complaint “the message takes too long to appear on the screen, the client must be really slow” only once. I don’t think this would be an issue.

Also, I think this is really easy to implement. If the echo-message capacity is enabled, just do not display your own messages in the buffer when the user sends them. Done.
