### ISSUE TITLE
weechat 2.8: autojoin before registration

### ISSUE THREAD

**Issue by klartext** [weechat/weechat#1467]
## Bug summary
weechat does connect, then uses autojoin before the registration as registered user has been done.
This yields in geeting a fallback-channel instead of the right channel.

## Steps to reproduce

1. register as user on freenode
2. set weechat to do the registering as user when connecting
2. set `#python` as autojoin channel for freenode
3. connect to freenode

## Current behavior
Connection works
registering works
autojoining works for channels which does not require to be a registered user
autojoining does not work for channels which require to be a registered user

## Expected behavior
Connection works
registering works
autojoining works for channels which does not require to be a registered user
autojoining works for channels which does require to be a registered user

## Suggested solutions
If user is registered on the server, then
autojoining channels should wait until registering as user has been completed.

## Additional information

---

- WeeChat version: weechat 2.8 (Arch install: weechat 2.8-1)
- OS, distribution and version: Arch Linux, 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 GNU/Linux

**Comment by flashcode** [comment]
Hi,

This is not a bug for me.

WeeChat autojoins channels immediately after connection, except if you set the option `irc.server.freenode.command_delay` to some seconds as delay (see `/help irc.server.freenode.command_delay` for more information).

But if possible, I recommend to use SASL for authentication. With that, the autojoin is always made after authentication, due to the way SASL is performed (it's the first thing done before anything else).
See the quickstart guide: https://weechat.org/files/doc/devel/weechat_quickstart.en.html#add_irc_server

**Comment by dv1** [comment]
Please add this information to the documentation. Furthermore, SASL is not available on OFTC.
