### ISSUE TITLE
Relay protocol: Password hashing with nonce

### ISSUE THREAD

**Issue by AStove** [weechat/weechat#1474]
This is about the [relay protocol init command](https://weechat.org/files/doc/stable/weechat_relay_protocol.en.html#command_init).
The current design of the password hashing has no purpose because the hash never changes. Knowing the hash gives the exact same authority as knowing the password.

To improve this, the relay server (weechat) could send out a nonce (different for each connection) which the relay client combines with the password and hashes. The server does the same locally to check if the hash is valid.

In order to get the nonce from the server to the client there needs to be a message before the init command. Perhaps this message can also include the server version so the client can adjust it's behaviour according to the capabilities of the server. I'm unsure if such a capabilities message would break older relay clients or not, it shouldn't.

Please correct me if I'm wrong about any of this.

Edit: Ok, the hashing is to prevent brute-forcing, not evesdropping on the connection. I get it now, but still.

Edit2: There doesn't seem to be configuration options to turn off doing init with the normal password. Therefore this is again useless against brute forcing. The attacker will just take the normal password login option.

**Comment by mhoran** [comment]
Hey @flashcode this is great. @oakkitten and I are wondering what the best path forward is for weechat-android and weechatRN, especially given the security implications.

Given we do not know whether the weechat we're connecting to actually supports the `handshake` command, we can only guess as to whether it's supported, e.g. with a timeout. That means a smart attacker could inject themselves in the middle and not reply to our `handshake`, and we would send an `init` with a plaintext password. That would circumvent this feature.

We could add an option to our clients that *forces* the use of a handshake, but I am always against introducing new options, especially security related ones. I'd love for this to be as automatic as possible.

As far as I know, it's not possible for us to figure out the version of weechat running on the other side before `handshake` (or `init`). That might be a big change to make in the relay protocol, but it would allow us to work around a potential security issue here.

Or maybe I (we) are completely misunderstanding this feature and the security implications. Happy to be wrong!

**Comment by oakkitten** [comment]
while we are at it, is there a way to disable the handshake command? i assumed that the reason weechat didn't reply to a wrong password in the first place was to make the presence of weechat undetectable and i'm not sure that benefits of this outweigh the cost

**Comment by flashcode** [comment]
@mhoran: good questions and there's no easy solution, because we want to keep backward compatibility.
Sending the WeeChat version before the authentication solves one problem, but in term of security I'm not for, it would let anyone know you have a version affected by vulnerabilities.
We could discuss further about pros and cons of solutions on #weechat if needed.

**Comment by flashcode** [comment]
@oakkitten: disabling handshake would mean force the use of plain text password, which is probably not what we want in term of security.
Are you sure it's really a problem to know you're connected to a WeeChat? The handshake replies with info strictly needed to authenticate, nothing more.

**Comment by AStove** [comment]
The websocket path is literally "weechat" by default. Also, security by obscurity is not to be relied on. If a portscanner now finds an port, creates a websocket, sends an init to it and sees the socket closed by the server, the attacker also knows that there's a weechat there.

**Comment by oakkitten** [comment]
a websocket isn't the only way to connect to relay. i was assuming (wrongly) that the lack of the error message was intentional. i mean, it's still pretty bad UX. also i assumed that weechat would break off the connection on anything but a good init command, which is also wrong, apparently. so i guess you could always detect weechat anyway so this is not an issue

by the way, is there a reason to support sha256 if you support sha512?

**Comment by flashcode** [comment]
SHA256 is there just in case a client can not generate SHA512 (which should rarely happen), no other reason.

**Comment by oakkitten** [comment]
by the way, while you probably can't DoS WeeChat with this, you can render it nearly unusable. simply flood it with bogus attempts to login using pbkdf2, and it will use 100% of CPU and hang for seconds at a time. if `relay.network.max_clients` is set to an high number, you can hang WeeChat for minutes at a time, which will kick you off networks...

**Comment by flashcode** [comment]
@oakkitten : I can add an option to limit the number of new clients per minute, with for example a default value of 5. But this could prevent yourself from connecting, in case other people are trying to connect frequently on your relay, so I'm not sure if that's the best solution.
I could also limit the number of connections from a same IP address in a given time.

**Comment by JeremyMahieu** [comment]
1.  Move computational difficulty on the client side only. The server should basically have a lookup table of correct hashes and not be forced to do x cycles of hashing every time someone logs on. The "client nonce" prevents this and I honestly don't know what it's purpose is. It forces the server to redo the calculation each time.
2. Rate limiting per client IP. Because malicious clients tryign to DoS don't need to send correct hashes, as long as they get the server to check them.
3. Global rate limit for DDoS.

**Comment by oakkitten** [comment]
while this might be an attack vector it is probably not very dangerous. i could hang WeeChat for a long time, but it required setting `relay.network.max_clients` to 100, also you have to coordinate the `init` calls. otherwise WeeChat becomes very slow but you can still switch buffers and type etc, so you can hopefully turn off the relay plugin or something like that

> The server should basically have a lookup table of correct hashes

wouldn't this open up the connection to replay attacks? and yeah, what's the purpose of client nonce?

...i think you can rate-limit incoming connections with `iptables`? not sure if rate-limiting is WeeChat's job. maybe somehow marrying it to `fail2ban` is a good idea?

by the way even if you don't force WeeChat to do the calculations (e.g. by sending wrong nonce) you can still easily get it to use 100% CPU. it won't be hanging up but still 100% isn't good is it?

**Comment by JeremyMahieu** [comment]
>wouldn't this open up the connection to replay attacks? and yeah, what's the purpose of client nonce?

Not if you mix in the server nonce at the last hash round. Server stores the N-1 hash and then only needs to do one round of hashing.

If you do it like that you also need a salt that's mixed with the hassword at the beginning of the hashing to protect against rainbow tables.

Anyway, there has to be some off the shelf algorithms that can be used.

**Comment by oakkitten** [comment]
> Server stores the N-1 hash

if i get this right, the attacker could then try guessing the N-1 hash, couldn't they? that would be like having a 512 bit password. much better than a regular password but i'm not sure how it compares with iterations

**Comment by JeremyMahieu** [comment]
Yes trying to guess 512bit random key vs dictionary attack with N hash cycles. Both are probably hard enough.
