### ISSUE TITLE
Option to limit characters in input

### ISSUE THREAD

**Issue by hello-party** [weechat/weechat#1489]
## Feature description

At times a user can accidentally paste a large amount of text without line breaks, causing a flood. Currently, weechat or the protocol automatically splits at 403 characters. It would be handy to have a pre-set character limit for all lines without spaces (e.g. an image that is accidentally copy and pasted.) 

Having one line of code vs a dozen would prevent accidental floods.

I am proposing two options:

* a hard character limit for the input (e.g. 403 characters)
* an on/off option to only restrict on text without spaces

**Comment by trygveaa** [comment]
> At times a user can accidentally paste a large amount of text without line breaks, causing a flood.

What kind of flooding do you mean? WeeChat won't send any message until you press enter. I tried pasting 30000 characters in WeeChat, and while it hanged for a few seconds, there was no flooding.

> Currently, weechat or the protocol automatically splits at 403 characters. It would be handy to have a pre-set character limit for all lines without spaces (e.g. an image that is accidentally copy and pasted.)

Only the irc plugin splits the line.

> e.g. an image that is accidentally copy and pasted.

Does your terminal really paste a bunch of text of you have an image on the clipboard? This sounds like something you should fix in the terminal.

**Comment by hello-party** [comment]
>What kind of flooding do you mean?

It'll happen if you accidentally `Copy Image` instead of `Copy Image Address` -- pasting and hitting enter immediately. It's a rare case, but I've seen this happen with a variety of clients (not just terminal based.)

**Comment by trygveaa** [comment]
> It'll happen if you accidentally Copy Image instead of Copy Image Address -- pasting and hitting enter immediately.

This doesn't happen for me in any of the terminal emulators I've tried. If I have an image on the clipboard, pasting doesn't do anything (except for konsole and qterminal, in those a link to the image will be pasted if the image was copied from a browser, otherwise nothing happens for those too). Which terminal emulator have you experienced this in?

> not just terminal based

WeeChat is a terminal based program. If you're talking about any of the relay clients, I'd say the issue should be solved there.

**Comment by hello-party** [comment]
this is a seemingly random issue that isn't isolated to weechat. I've seen it happen with Textual/Limechat users, for instance.

I just thought this would be a handy feature for weechat and was asked to post it here.

**Comment by AStove** [comment]
This happens when for example you do Copy Image Address directly in the preview of google and the image was a base64 encoded image. It then copies 10k characters. But still you need to confirm with (ctrl-Y) before it starts flooding. But I admit, I have personally done this once. [Example google search](https://www.google.com/search?q=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F48674256%2Fsome-base64-usage-in-ruby-is-this-a-good-use-case&tbm=isch&ved=2ahUKEwi9oae-r7PpAhX1wQIHHUJIBhIQ2-cCegQIABAA&oq=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F48674256%2Fsome-base64-usage-in-ruby-is-this-a-good-use-case&gs_lcp=CgNpbWcQA1D2oQJY9qECYJSoAmgAcAB4AIABOYgBOZIBATGYAQCgAQGqAQtnd3Mtd2l6LWltZw&sclient=img&ei=rDu9Xr2bEvWDi-gPwpCZkAE&bih=937&biw=1920&rlz=1C1GCEU_enBE845BE845)

**Comment by trygveaa** [comment]
So you mean if you paste, and then press enter (if it's a single line) or ctrl-y (if it's multiple lines)?

**Comment by AStove** [comment]
Yes, I've done it, it does happen. But I also agree that this is enough of a warning, there should be no change to this. 

I just wanted to clarify how it could happen the copying of images leading to long strings of text.

**Comment by trygveaa** [comment]
Maybe the irc plugin could have an option for a confirmation when you try to send a line that would be split into multiple lines. I think that would be a better solution than a hard limit on the input.

The irc plugin is the one that splits the line into multiple, so I think it's better fitting to have something there than in core. Sending long lines isn't necessarily a problem in other plugins/scripts.

**Comment by trygveaa** [comment]
> I just thought this would be a handy feature for weechat and was asked to post it here.

By the way, I'm not a part of the weechat team, so don't take my comments to mean that this is something they don't want, or something not suited for weechat. I just wanted to discuss the reason for needing it, to figure out if it's a good idea, or if a better solution to the problem could be found.

**Comment by hello-party** [comment]
Okay, this works. We can use some basic regex to catch the base64 encoded image.

1. install text_replace.py
2. `/set plugins.var.python.text_replace.replacement_words "data:image.*="`
