### ISSUE TITLE
color_nick_offline does not affect /me

### ISSUE THREAD

**Issue by NoSuck** [weechat/weechat#1492]
# Steps to reproduce

1. `/set weechat.look.color_nick_offline on`
2. `/me is hungry.`
3. `/part`

## Current behavior

The nick that replaces `/me` stays the same color.

## Expected behavior

The nick's color would change to `weechat.color.chat_nick_offline`.

---

- WeeChat version: 2.8, Mar 31 2020 22:07:29
- OS, distribution and version: Linux 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux

**Comment by flashcode** [comment]
Hi,

This is not really a bug (even if it can be considered as a bug).

The nick in `/me` messages is displayed in the message itself, not in the prefix. And the option `weechat.look.color_nick_offline` affects only nicks displayed in prefix.

To fix that it would require breaking changes because WeeChat (core) does not know that irc plugin writes a nick name in the message itself.
So IRC should print `/me` messages differently to use the message in the prefix, but this would lead to major display changes, and a redesign of `/me` messages.

For now I may just close this as "won't fix", since it's not a major issue for me.

**Comment by NoSuck** [comment]
Thank you for the details.  I figured as much.  Also, I can't imagine it would be a major issue for *anyone,* really.

May this issue remain as a search hit for future `color_nick_offline` searches.
