### ISSUE TITLE
how to add support for another http-based protocol backend?

### ISSUE THREAD

**Issue by Al-Caveman** [weechat/weechat#1559]
## Question
hi — there is a http/html/js/etc (website) chat server that i'd like to add it as a backend to my weechat, so that i can go there without needing a web browser.  

what's the best way of doing this?

my code will be doing some translation between the nasty side (i.e. http/html/js/... yuck!) and weechat.  

the main reason i'm interested in weechat is that it already has an ncurses interface.  so if it is easier for me to re-use weechat's i'll.  but if it turns out that making my own custom ncurses ui is cheaper, then i may just use ncurses.

---

- WeeChat version:  n/a
- OS, distribution and version: gentoo/arch linux.

**Comment by flashcode** [comment]
Hi,

You could add this as a script (you can choose the language, all supported languages are using the same API).
If you prefer C, this is of course also possible (the base API is written in C, there are wrappers for scripting languages over this API).

Be careful on one point, the HTTP or any network blocking call must be done with the appropriate API function (eg: hook_process or hook_process_hashtable), so the call is made in background without blocking WeeChat.

There are existing protocols supported via scripts like:

- https://weechat.org/scripts/source/slack.py.html/
- https://github.com/poljar/weechat-matrix

**Comment by poljar** [comment]
I would like to add that because the HTTP requests needs to be done in a separate process using `hook_process` it becomes a bit cumbersome to implement HTTP based protocols. Another thing that quickly expands the complexity of a HTTP based protocol implementation is the requirement to do request chains, at least in Matrix it was so. Request chains have lead to callback hell in weechat-matrix quite a bit.

Thus, to escape callback hell and allow easy usage of thread and connection pools inside of Weechat, [Rust bindings](https://docs.rs/weechat/0.3.1/weechat/) for the Weechat plugin API were born.

The bindings aim to be safe (in the Rust sense of secure) and a bit higher level than the C plugin API, for example instead of moving pointers to traverse an infolist, an [iterator](https://docs.rs/weechat/0.3.1/weechat/infolist/index.html#examples) can be used.

But perhaps the coolest thing of the Rust bindings is the async/await syntax support, this mitigates the callback hell for Matrix quite a bit. You can directly send out a request from your buffer callback and await its completion, an example of this can be found [here](https://github.com/poljar/weechat-matrix-rs/blob/master/src/room_buffer.rs#L116).

There are two HTTP based protocol implementations using the Rust API bindings:
* https://github.com/poljar/weechat-matrix-rs/
* https://github.com/terminal-discord/weechat-discord
