### ISSUE TITLE
Add support for the 'tls' IRCv3.1 capability

### ISSUE THREAD

**Issue by nyuszika7h** [weechat/weechat#157]
http://ircv3.org/extensions/tls-3.1
https://github.com/ircv3/ircv3-specifications/blob/master/extensions/tls-3.1

**Comment by Mikaela** [comment]
This seems to be the only IRCv3.1 capability not supported by WeeChat and also the less supported capability.

* http://ircv3.net/specs/extensions/tls-3.1.html
    * the link in original submission seems dead to me. `ERR_NAME_NOT_RESOLVED`
* http://ircv3.net/software/clients#Desktop%20Clients
    * list of clients & supported capabilities

**Comment by Mikaela** [comment]
Are there any plans on how this is going to get implemented? I have some ideas.

* New command and options: /starttls (to make it easier for users, not necressarily needed) & `irc.server_default.starttls` and `irc.server.NETWORK.starttls`.
* When the TLS capability is seen print in core (because it wouldn't be seen in server) "freenode supports STARTTLS, to enable it use /starttls enable freenode".
* /starttls enable would turn on irc.server.freenode.starttls and STARTTLS would be used for freenode immediately after setting and in all the future connections.
    * freenode would be optional server argument and running the command in freenode buffer would only need /stattls enable

How the option behaves needs more thinking though:
* believe that the server supports STARTTLS when enabled (easier and probably more in spirit of the spec)
* only use STARTTLS when server has seen supporting it (more difficult as whether the server supports TLS must be remembered elsewhere, but in this case the option should have warning to only use it on networks which have STARTTLS).
    * this probably doesn't have so much benefit anyway as it would be too radical change as default.

How the *explicitly plaintext* mentioned in the specification works I have no idea as WeeChat requires both to be configured explicitly, but I don't think there would be any harm in printing the text in all plain text connections, it would just be one line per server.

**Comment by mxl** [comment]
Does weechat support STARTTLS extension for xmpp?

**Comment by lol768** [comment]
Suggest close in favour of https://github.com/weechat/weechat/issues/1087

**Comment by flashcode** [comment]
Closing as the specification is deprecated and should not be implemented.
