### ISSUE TITLE
problem with if in the command option of a trigger

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1579]
## Bug summary

hard to explain so i'll jump right to the steps to reproduce

## Steps to reproduce

1. /trigger add comm command comm "" "" "${if:a==b?a};/print -core hello"
2. /buffer 1
3. /comm

## Current behavior

it display the message _You can not write text in this buffer_ followed by _hello._ I thought this was because the conditions a==b is false and there is nothing to do when the conditions is false so this is replaced by nothing but the following works (also note that it does that only on core buffer, it send nothing else than hello on a channel)

1. /trigger addreplace comm command comm "" "" ";/print -core hello"
2. /buffer 1
3. /comm

there is a ; before /print but still works. I encounter this issue so many times i cant count (using an ${if in the command option of a trigger but not specifying a value if the conditions is false because it doesn't make sense).

## Expected behavior

an ${if in the option command of a trigger should not cause weechat to write _You can not write text in this buffer_ when typing the command in core buffer

---

- WeeChat version: WeeChat 3.0-dev (git: v2.9-66-g0ff08e54f) [compiled on Oct 21 2020 18:25:21]
- OS, distribution and version: Debian 10
- Terminal: urxvt
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Hi,

I would say it's the normal behavior (but this can be discussed), I explained below what happens.

First you can reproduce with this command:

    /eval -s ${if:a==b?a};/print -core hello

which displays:

    You can not write text in this buffer
    hello

while this command:

    /eval -s ;/print -core hello

just displays:

    hello

This is because when WeeChat splits the commands on the semicolons, empty commands are ignored, so when command is `;/test` the leading `;` is ignored and the only command executed is `/test`.

But when you have anything before the first semicolon, it's used as the first command. The evaluation is done after the split, and then if the result is an empty string, it's sent to the buffer. An empty string can be sent to function `weechat.printf`, it's a valid string. But there's one weird thing: an empty string sent to an IRC channel does nothing, while it displays an error on the core buffer, this should probably be fixed.

One way to fix the problem in your example would be to use `/mute` command in the "else" condition, ie:

    /eval -s ${if:a==b?a:/mute};/print -core hello

**Comment by pascalpoitras** [comment]
thanks! I didn't know we can use /mute this way, this works perfectly
