### ISSUE TITLE
wrong line selected when quoting a message if there's a root bar at the bottom and just one window

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1602]
## Bug summary

When quoting a message (m/q/Q) in cursor mode with a bottom root bar and a single window, the selected line is not the correct one

## Steps to reproduce

1. weechat -t
2. /bar add nicks root bottom 7 0 buffer_nicklist
3. /cursor go chat
4. quote the second line

but it works when there's more than one window

1. weechat -t
2. /bar add nicks root  bottom 7 0 buffer_nicklist
3. /window splith
4. /cursor go chat
5. quote the second line

## Current behavior

doesn't select the correct line

## Expected behavior

select the correct line

## Note

aloo_shu provide a workaround for this bug
`
/trigger addreplace fix command_run "/cursor go chat" "" "" "/window page_up;/window page_down"`

---

- WeeChat version: WeeChat 3.1-dev
- OS, distribution and version: Debian Buster
- Terminal: urxvt
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by alooshu** [comment]
apparantly, the bug isn't related to the root bar at all. I can get it by -starting weechat -t, -setting the terminal resolution low enough so that lines begin breaking, -entering /cursor go chat mode, -picking the SECOND line from the top and attempting to quote (q|Q|m) it. One of the broken lines is getting picked instead of the chosen one.

**Comment by alooshu** [comment]
apparantly, the bug isn't related to the root bar at all. I can get it by -starting weechat -t, -setting the terminal resolution low enough so that lines begin breaking, -entering /cursor go chat mode, -picking the SECOND line from the top and attempting to quote (q|Q|m) it. One of the broken lines is getting picked instead of the chosen one.

**Comment by flashcode** [comment]
This regression seems related to commit 93d2dbf3e1ef30e676a6edd56ab2b9bd2ddd70d9, I'm looking for a fix that is compatible with the initial fix.
