### ISSUE TITLE
SASL mechanism: SCRAM-SHA-256

### ISSUE THREAD

**Issue by ircnet-com** [weechat/weechat#1628]
## Feature description
The IRCv3 working group now recommends SCRAM-SHA-256 as SASL authentication mechanism instead of ECDSA-NIST256P-CHALLENGE. I also set up a service which has SCRAM-SHA-256 as the primary mechanism. Could you implement it too? It should be easy if you use gsasl.

GNU SASL Library - Libgsasl: https://www.gnu.org/software/gsasl/
Python IRC implementation: https://github.com/jesopo/bitbot/blob/master/src/core_modules/ircv3_sasl/scram.py

**Comment by flashcode** [comment]
Do you know any server supporting SCRAM-SHA-256, so I can test it while implementing it in WeeChat?

Thanks.

**Comment by ircnet-com** [comment]
Hi,

you can use irc.alphachat.net.

`:irc-us1.alphachat.net 908 * ECDSA-NIST256P-CHALLENGE,EXTERNAL,PLAIN,SCRAM-SHA-512,SCRAM-SHA-256,SCRAM-SHA-1 :are available SASL mechanisms`

Register at nickserv and then use the credentials in SASL.

Recently I have coded a ZNC module that uses gsasl:
https://github.com/ircnet-com/misc/tree/master/znc-modules/gsasl

After server's final message (v=..) we have to send this to complete:
`AUTHENTICATE +`

Thank you
Patrick

**Comment by aaronmdjones** [comment]
Note that you should *verify* the `server-final-message` before sending `AUTHENTICATE +`.

Failure to verify must result in an abort (`AUTHENTICATE *`), and then disconnecting if `irc.server.foo.sasl_fail` is set so. I also highly recommend warning users that the verification failed; which is evidence that they have connected to a network that has not had knowledge of the password. The reason for alarm is that you have just disclosed enough information to mount a brute-force search for the password. If you are connected to the *correct* network, it will not send `server-final-message` if you configured the wrong password, instead aborting the exchange.

**Comment by flashcode** [comment]
I wonder one thing, is there an interest in supporting SCRAM-SHA-1?
Technically it's very easy to support in addition to SHA-256 and SHA-512.

But are there a lot of servers that support only SCRAM-SHA-1and not one of the others?

I'm not fan in general to add weak hash algorithm support, but it's possible to do it and recommend to not use it, just to be flexible.

**Comment by aaronmdjones** [comment]
When I worked with @jwheare on adding SCRAM support to IRCCloud, we came up with the idea that clients performing a password-based SASL login should prefer `SCRAM-SHA-512`, `SCRAM-SHA-256`, `SCRAM-SHA-1`, and `PLAIN`, in that order.
When @jesopo was adding SCRAM support to BitBot, a pseudo-mechanism was created that does the same thing; when you set it to use that mechanism, which doesn't actually exist, it behaves the same way.

Specifically, the behaviour is as follows:

- The client has been configured to use a password-based SASL mechanism, but not any one mechanism in particular
- Start out with the mechanism list `SCRAM-SHA-512,SCRAM-SHA-256,SCRAM-SHA-1,PLAIN`
- Connect to the IRC server and request its capabilities
- If it does not advertise the `sasl` capability:
  - Give up, and
  - If `irc.server.foo.sasl_fail` is set to `disconnect`, disconnect now
- If it does advertise the `sasl` capability;
  - If it advertises its supported mechanisms, modify the list to remove the mechanisms that the server doesn't support:
    - If the list of mechanisms is now empty, the server does not support any password-based SASL mechanisms:
      - Give up, and
      - If `irc.server.foo.sasl_fail` is set to `disconnect`, disconnect now
    - If the list of mechanisms is not empty, immediately try the first mechanism in the list
  - If it does not advertise its supported mechanisms, immediately try the first mechanism in the list
- If you are trying to negotiate an unsupported mechanism, you will receive a `908` numeric with the supported mechanisms
  - Modify the list to remove the mechanisms that the server doesn't support, and
  - Make a note that you received a `908` numeric
- If you receive a `904` numeric:
  - If you previously received a `908` numeric:
    - Remove the note of this, and
    - Retry with the first mechanism in the list
  - If you did not previously receive a `908` numeric:
    - Give up, and
    - If `irc.server.foo.sasl_fail` is set to `disconnect`, disconnect now
- If, after sending `client-first-message`, you receive a `908` numeric:
  - You are trying with a mismatched digest algorithm (for example, you are attempting `SCRAM-SHA-512`, but the server is storing credentials by hashing them with SHA-256 or SHA-1)
    - Modify the list to remove the mechanisms that the server doesn't support, and
    - Make a note that you received a `908` numeric
- If, after sending `client-first-message`, you receive a `904` numeric, or you receive a SCRAM error (`e=...`):
  - If you previously received a `908` numeric:
    - Remove the note of this, and
    - Retry with the first mechanism in the list
  - If you did not previously receive a `908` numeric:
    - If `irc.server.foo.sasl_fail` is set to `disconnect`, disconnect now, or
    - This could be for any number of reasons, including:
      - The user's services account is frozen, or
      - The user's services account was dropped after negotiation began, or
      - The user's password hash is not in a PBKDF2 format, so SCRAM authentication cannot proceed, or
      - There is some other problem specific to this user's account, or this login attempt
    - Therefore, fall back to trying SASL `PLAIN`
- If, after sending `client-first-message`, you receive `server-first-message`, you know that you are using the correct, supported SCRAM mechanism for this user
  - Throw out your mechanism list and all fallback logic at this point, and
  - Continue with the exchange (send `client-final-message`)
- If, after sending `client-final-message`, you receive a `904` numeric, or a SCRAM error (`e=...`):
  - Give up, and
  - If `irc.server.foo.sasl_fail` is set to `disconnect`, disconnect now
- If, after sending `client-final-message`, you receive `server-final-message`:
  - If verification of `server-final-message` fails:
    - Give up, and
    - Warn the user that they have just connected to a malicious server, and have disclosed enough information for the adversary to perform an offline brute-force search for their password, and
    - If `irc.server.foo.sasl_fail` is set to `disconnect`, disconnect now
  - If verification of `server-final-message` succeeds:
    - Complete the negotiation (by sending `AUTHENTICATE +`), and
    - Adjust the user's configured SASL mechanism to the mechanism that just succeeded, so that all of this logic is not repeated for subsequent logins

As you can see, this is quite complicated, and so you can be forgiven for not wanting to implement that, and instead force the user to choose an explicit mechanism upfront. However, if you would like to do this, I would be happy to give you access to my testnet so that you can exercise all of these paths.

You should support `SCRAM-SHA-512` and `SCRAM-SHA-1` as well. It is only a matter of using different digest algorithms.

**Comment by aaronmdjones** [comment]
Also note that `SCRAM-SHA-1` is not weak. It uses PBKDF2, which uses HMAC, which renders the underlying digest algorithm immune to many attacks. HMAC-MD5 is still secure for the same reason.

**Comment by aaronmdjones** [comment]
Finally, note that if you choose to implement the logic described above, you should not explicitly configure the user's mechanism to `PLAIN` if a fallback to `PLAIN` succeeds; the reason for this is that a server will only advertise SCRAM mechanisms if it actually intends to support them, and a `PLAIN` login can get the user's account into a state where a future SCRAM login will succeed (for example, by converting their password hash to a usable format).

**Comment by Neustradamus** [comment]
@ all : I wish you a Happy New Year 2022!

I am very happy to see this ticket about SCRAM, thanks a lot!

@flashcode: Thanks for your commits:
- https://github.com/weechat/weechat/search?q=scram&type=commits
- https://github.com/weechat/weechat/search?q=sasl&type=commits
- https://github.com/weechat/weechat/commit/5cffb7179fee6d70d5c8cee5b5c18ec51f1272f6
- https://github.com/weechat/weechat/commit/e365e66eebeeb01ad88f0b9e3f17b135c21afc82
- https://github.com/weechat/weechat/commit/8c57e8abd3474a23d8117ef38160b486e9a49538
- https://github.com/weechat/weechat/commit/f8872c415b292111515f1a62d1dda5b6eb687f1c
- https://github.com/weechat/weechat/commit/791b910a77b24053309d2ae308aed37da0da166c

A long time ago, I have requested at @irssi team without success, I will relaunch.

Linked to:
- https://github.com/scram-xmpp/info/issues/1
https://github.com/weechat/weechat/issues/1628
- https://github.com/weechat/weechat/issues/1679
