### ISSUE TITLE
WeeChat's SASL SCRAM-SHA-256 implementation is broken

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1679]
## Bug summary

WeeChat will not respond to server side challenge instead sending CAP END and fails SASL SCRAM-SHA-256 authentication. 

## Steps to reproduce

1.`/server add testnetergo testnet.ergo.chat/6697 -ssl`
2. `/set irc.server.testnetergo.sasl_username scramtest`
3. `/set irc.server.testnetergo.sasl_password qRpBUqWjv8tBQZjUyEWh8g`
4. `/set irc.server.testnetergo.sasl_mechanism scram-sha-256`
5. `/connect testnetergo`

## Current behavior

`=!= irc: SASL error: protocol error`

and in raw log it's seen that server challenge goes unanswered while WeeChat sends CAP END instead.

## Expected behavior

SASL Authentication succeeds

## Suggested solutions

Fixing SCRAM-SHA-256 implementation to reply to the server's challenge.

## Additional information

slingamn from Ergo has helped in figuring this issue out and created the test details.

---

- WeeChat version: WeeChat 3.3-dev (git: v3.2-97-g72a9b87c1) [compiled on Aug  1 2021 23:07:53]
- OS, distribution and version: Debian GNU/Linux 11 (bullseye)
- Terminal: MATE Terminal
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment]
Hi,

In fact, the authentication fails because WeeChat has issues to parse the AUTHENTICATE message received:

    --> testnetergo | @time=2021-08-03T16:30:10.175Z :testnet.ergo.chat AUTHENTICATE cj1FRjFuMFFyZmhVN(…)

The time tag is not a problem, but the ":testnet.ergo.chat" is not expected here (so WeeChat uses "AUTHENTICATE" instead of the base64 value, which of course leads to an authentication error).

Is it possible/allowed in IRC protocol to have such prefix before the AUTHENTICATE command?

I can fix, this is just to be sure it's a "normal" use case and this can happen on a real server (not a testing one).

**Comment by flashcode** [comment]
Thanks, fixed.
