### ISSUE TITLE
do not autoload editor backup files

### ISSUE THREAD

**Issue by ksu-0** [weechat/weechat#1698]
Many popular editors, including Vim and Emacs, create backup copies of files with ~ appended to their name. Please consider not autoloading scripts with such a file name.

**Comment by weechatter** [comment]
you mean, when a backup file is in autoload folder (eg python/autoload/~myscript.py) ?

**Comment by ksu-0** [comment]
Yes, and it's `python/autoload/myscript.py~`.

**Comment by flashcode** [comment]
I think instead of excluding some extensions, the scripting plugins could be more strict when auto-loading scripts and check strictly the expected file extension, ie:

| Language   | Extension |
| ---------- | --------- |
| Python     | `.py`     |
| Perl       | `.pl`     |
| Ruby       | `.rb`     |
| Lua        | `.lua`    |
| TCL        | `.tcl`    |
| Scheme     | `.scm`    |
| PHP        | `.php`    |
| JavaScript | `.js`     |

**Comment by ksu-0** [comment]
Sounds good for me.
