### ISSUE TITLE
Drop support for SASL DH-BLOWFISH and DH-AES

### ISSUE THREAD

**Issue by maxteufel** [weechat/weechat#175]
Both mechanisms are vulnerable to MITM attacks when not connecting using SSL and make some users think it provides the same security as SSL. Atheme recently removed support for `DH-BLOWFISH` and `DH-AES`, see atheme/atheme@15f6d84

Users should use `PLAIN` over SSL or `EXTERNAL` for secure authentication. Additionally, WeeChat could add support for `ECDSA-NIST256p-CHALLENGE`.

**Comment by flashcode** [comment]
I'm reconsidering this issue, and we should remove DH-BLOWFISH and DH-AES, because:

* Many ircd removed support for them.
* Other SASL mechanisms are supported and can be used instead:
  * PLAIN (WeeChat ≥ 0.3.2)
  * SCRAM-SHA-1 (WeeChat ≥ 3.2)
  * SCRAM-SHA-256 (WeeChat ≥ 3.2)
  * SCRAM-SHA-512 (WeeChat ≥ 3.2)
  * ECDSA-NIST256P-CHALLENGE (WeeChat ≥ 1.2)
  * EXTERNAL (WeeChat ≥ 0.3.8)
