### ISSUE TITLE
adding sort to eval

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1782]
## Feature description

It would be a nice addition to ${split:...} to be able to sort the list
so for example ${split:1, ,sort,test hello word} gives hello

**Comment by pascalpoitras** [comment]
finally I think it might be better to add ${sort:...} instead of changing split

**Comment by pascalpoitras** [comment]
it could works like this

${sort:sort_type,order,case_sensitivity,separator,list}

**sort_type:** number or string
**order:** ascending or descending
**case_sensitivity:** 0 or 1
**separator:** empty for comma
**list:** list of element separated by **separator**

**Comment by flashcode** [comment]
I'm considering a way to make easier the call to script functions, so that we've not to reimplement the wheel inside WeeChat, like this sort function, which is widely available in all scripting languages supported.

For example we could be able to call the `sort` or `sorted` Python functions from eval string, with the easiest possible syntax.

**Comment by weechatter** [comment]
means, you have to load at least one scripting plugin, no?

**Comment by flashcode** [comment]
@weechatter: yes.
