### ISSUE TITLE
while loop in eval

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1816]
## Feature description

Now that we have `${define:...}`, it would be possible to create a `${while:...}` ?

for example

`/item add test "" "${define:i,1}${while:${i}<10?${i}${\n}${define:i,${calc:${i}+1}}}"`

would create an item with ten numbered lines

**Comment by flashcode** [comment]
Hi,

Evaluated strings are not a language, so I'm not sure adding such loop instructions is a good idea, because:

- What would happen if you make an infinite loop? New mechanisms would have to be implemented to prevent that, and it could be complex.
- `while` is just a way to make a loop, I'm afraid all other languages loops, functions, macros, etc. would be asked as well if `while` is added.

For such need, I would suggest to use any of the supported scripting languages, which has everything you need (and much more!).
