### ISSUE TITLE
Window/Terminal title reset on redraw/resize

### ISSUE THREAD

**Issue by Deltafire** [weechat/weechat#1835]
## Bug summary
Since v3.7 Weechat now resets the window/terminal title on screen refresh (Ctrl-L) and resize events. This overrides any custom titles that may have been set in the terminal software or multiplexer.

## Steps to reproduce

1. Run Weechat inside Tmux
2. Hit tmux prefix then , (comma) to set a custom title.
3. Resize the terminal window

## Current behavior
Title is reset to  weechat.look.window_title.

## Expected behavior
Title should remain unaltered.

## Suggested solutions
None.

## Additional information
This change was introduced in commit 36d2e74 .

---

- WeeChat version: 3.7
- OS, distribution and version: Gnu/Linux, Ubuntu 18.04.
- Terminal: Tested with PuTTY, KiTTY and Iterm2.
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by ksu-0** [comment]
The change comes from fixing issue #1702.

From reading the documentation, current behavior is correct. If you do not want Weechat to set the window title, you can either not set `weechat.look.window_title` or (since the option is evaluated), set it so it evaluates to empty string in tmux.

**Comment by tzvetkoff** [comment]
Current behavior is incorrect.

The problem actually comes from [gui-curses-window.c:2535](https://github.com/weechat/weechat/blob/master/src/gui/curses/gui-curses-window.c#L2535-L2536) - as you can see, empty/unset `weechat.look.window_title` means it will always say `"Terminal"` rather than keeping it *unchanged*.
