### ISSUE TITLE
/autojoin apply sorts channels in opening order

### ISSUE THREAD

**Issue by ksu-0** [weechat/weechat#1876]
## Bug summary

`/autojoin apply` sorts channels in the order they were opened. I believe they should be sorted in their `/buffer list` order.

## Steps to reproduce

* `/join #a`
* `/join #b`
* `/buffer swap #a #b`
* `/autojoin apply`

## Current behavior

Autojoin is set to `#a,#b`.

## Expected behavior

Autojoin is set to `#b,#a`.

## Additional information

- WeeChat version: 3.8
- OS, distribution and version: Debian testing
- Terminal: xfce4-terminal
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
Hi,

This is not a bug for me, but like this by design: the order of your buffers has no link with the autojoin option (layout and such features are builtin and not linked to the irc plugin).

As a workaround, I could propose to add extra option in the `/autojoin sort` command to use the existing buffers as sort, something like:

- `/autojoin sort` → sort autojoin alpbabetically
- `/autojoin sort buffer` → sort autojoin based on buffer number for each channel

But then it must be done manually.

Note: you still have another solution to use `/layout` to force channel positions, whatever you have defined in the `.autojoin` option.

What do you think of this?

**Comment by ksu-0** [comment]
Having separate command to sort autojoin channels based on the buffer order is ok for me.

**Comment by flashcode** [comment]
Now you can do `/autojoin sort buffer`, and it sorts like this:

* channels with key are first in list (required by the IRC protocol)
* sort on buffer number, if a channel has no buffer, it's put at the end of list
* if multiple channels have same buffer number (or don't have a buffer), they are sorted alphabetically.
