### ISSUE TITLE
Why should /exit in any channel kill weechat itself?

### ISSUE THREAD

**Issue by dm17** [weechat/weechat#1910]
If I've hit this problem multiple times and still don't remember, then it must be a UX mismatch issue that others experience too. If a channel was joined within an IRC network, and an IRC network was connected to within weechat (IRC client), then why would `/exit` this many levels deep kill weechat, exiting all channels and IRC servers?

**Comment by flashcode** [comment]
Hi,

The command `/exit` is a WeeChat alias on command `/quit`, so this disconnects from all servers and quits WeeChat, and this is the expected behavior.
This is not an IRC command.

If you want to leave a channel, you can use the command `/part`.

If you don't like the alias `/exit`, you could:

- Remove the alias: `/alias del exit`
- Change exit alias to part channel: `/alias add exit part`
- Prevent accidental quit of WeeChat: `/ste weechat.look.confirm_quit on` (see `/help weechat.look.confirm_quit`)
