### ISSUE TITLE
UnrealIrcd x /help command

### ISSUE THREAD

**Issue by devnull-hub-lab** [weechat/weechat#1933]
## Feature description

Hi folks,

Unrealircd has its own help, provided by the help.conf module, but weechat have a built-in help.

So, "/help" command show different things in clients that read data help in unrealircd server and weechat client.

So, Is it possible to create a feature to consider the UnrealIrcd help server instead of the built-in weechat help when invoking the /help command?

Exemple, UnrealIrcd have default "/help usercmds" command. But weechat return "weechat =!= | No help available, "usercmds" is not a command or an option".

Thanks

**Comment by flashcode** [comment]
Hi,

The WeeChat command `/help` is supposed to be executed everywhere, even on IRC buffers where the server could have a command with the same name.

You have two ways to execute the HELP command on server:

- by using `/quote` command (used to send any command directly to the IRC server), for example: `/quote help usercmds`
- by doing an alias that do that for you, for example: `/alias add shelp /quote help`, then: `/shelp usercmds`.

It's not planned to have an automatic way to send help to WeeChat or server, because it's impossible in practice: WeeChat can not easily know that the server understands this command, and what about if you want to really use the WeeChat command and not the server one?

**Comment by devnull-hub-lab** [comment]
@flashcode 

Thanks for your reply!
If there was a help on the server, is complicated to Weechat identify it and replace weechat built-in help.
In other hand, there are some specific weechat commands, which are convenient to see and use.

"/quote help" worked, booth directly and by alias.

Thanks for help and clarification!
