### ISSUE TITLE
-o flag for trigger list and trigger listdefault

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#1953]
## Feature description

Would be nice to have a -o flag for `/trigger list`  and `/trigger listdefault` similar to `/plugin list -o` and `/script list -o`

It would print all the triggers name and the hook type for example

`beep (print), cmd_pass (modifier), cmd_pass_register (modifier)`

for `/trigger list` it might be useful to also tell apart defaults triggers from custom ones, maybe by using the following syntax

`beep (print,default), my_trigger(command,custom)`

**Comment by flashcode** [comment]
Here's what I propose:

- Do only for `/trigger list -o` and not `/trigger listdefault -o` because this list is the same for everybody, even if you changed the default triggers.
- Output will show only triggers enabled (is it needed to include disabled triggers?).
- Example of proposed output, supposing the default `beep` trigger has been customized and 2 triggers added (`my_line` and `my_config`):

```
Triggers enabled: beep (print, default, custom), cmd_pass (modifier, default), cmd_pass_register (modifier, default), msg_auth (modifier, default), server_pass (modifier, default), my_line (line), my_config (config)
```

**Comment by pascalpoitras** [comment]
sound good! thanks!

**Comment by flashcode** [comment]
In addition, these flags will be supported:

- `-o`: send list of triggers enabled to buffer (string in English)
- `-ol`: send list of triggers enabled to buffer (translated string)
- `-i`: copy list of triggers enabled in command line (for sending to buffer) (string in English)
- `-il`: copy list of triggers enabled in command line (for sending to buffer) (translated string)
