### ISSUE TITLE
Can't bind key ctrl-backspace (regression)

### ISSUE THREAD

**Issue by dorsiflexion** [weechat/weechat#1975]
## Bug summary

Ctrl-Backspace seems to be impossible to use as a key binding. This is a regression as it was possible prior to version 4.0.

## Steps to reproduce

1. Press `alt`+`k`, followed by `ctrl`+`backspace`.

## Current behavior

The output is: `backspace /input delete_previous_char`

## Expected behavior

The output is: `ctrl-backspace /input delete_previous_char`

## Suggested solutions

?

## Additional information

Alternatively:

`/key bind ctrl-backspace /input delete_previous_word` doesn't work either.

---

- WeeChat version: 4.0.1
- OS, distribution and version: Arch Linux
- Terminal: Alacritty 0.12.2
- Terminal multiplexer (screen/tmux/…/none):  none

**Comment by flashcode** [comment]
Hi,

This is intentional, but probably we're lacking some doc to explain how to do it.

In fact WeeChat can not reliably distinguish backspace from ctrl-backspace: both keys have different raw code, but WeeChat can now know which one is backspace and which one is ctrl-backspace.

Then one way to bind ctrl-backspace is to bind the raw key code, which could be ctrl-h (this one is ctrl-backspace for me):

```
/key bind ctrl-h /print ctrl-h
```

Then try to press backspace and ctrl-backspace, you should have a different behavior.

If not working, try:

```
/key bind ctrl-? /print ctrl-?
```

If working fine, I'll update `/help key` to mention this.

**Comment by trygveaa** [comment]
To add to that, the reason WeeChat can't know which of these keys is which is that in a terminal emulator, backspace and ctrl-backspace maps to the ctrl-h and ctrl-? keys. However, which maps to which depends on which terminal emulator you're using and the configuration of that terminal emulator. So when WeeChat receives ctrl-h or ctrl-? there's no way for it to know if it came from a backspace press or a ctrl-backspace press. For more details about this, see this discussion: https://comp.terminals.narkive.com/i3ywh6Rv/backspace-h-vs-linux-vs-terminfo

To figure out what your terminal emulator sends, you can run `/debug key` in WeeChat and press ctrl-backspace.

Technically, in some terminal emulators it is possible to reliably distinguish between these keys by enabling an alternate keyboard protocol. However, this is not something WeeChat supports.

**Comment by flashcode** [comment]
I propose to add this text in `/help key`:

```
For some keys you might need to use /debug key, that also displays
the raw key code that can be used as well (for example ctrl+backspace
could be ctrl-h or ctrl-?, depending on your terminal and other settings).
```

**Comment by dorsiflexion** [comment]
Binding `ctrl-h` works for me. Thanks a lot. 👌
