### ISSUE TITLE
draft/multiline command

### ISSUE THREAD

**Issue by runxiyu** [weechat/weechat#1992]
## Bug summary

On servers with IRCv3 `draft/multiline`, typing something in a channel buffer: If the first line of input starts with a slash (and is thus interpreted as a command), the following lines are sent in its raw form to the server.

## Steps to reproduce

1. Connect to a server that has `draft/multiline` and `/join #test`

2. Send the following at once (newline by meta+return):
   ```
   /part #test
   JOIN #test
   ```

3. Also try:
   ```
   /part #test
   PRIVMSG someone-else :Hello!
   ```

4. Also try:
   ```
   /part #test
   /join #test
   ```

## Current behavior

1. WeeChat joins the channel normally 
2. WeeChat parts #test and then joins it, sending `JOIN #test` as a raw message.
3. WeeChat parts #test and messages someone-else, saying "Hello!" by sending `PRIVMSG someone-else :Hello!` as a raw message.
4. WeeChat parts #test and sends `/JOIN #test` to the server, rather than interpreting `/join` as an actual command and sending `JOIN #test` (note that the connection's raw command shouldn't include a preceeding `/`)

## Expected behavior

I don't think it's expected that users could just send raw IRC messages without /quote this way.

Possible "better" behavior:
- If we're doing a multiline message (as in `PRIVMSG`) or anything else that supports `draft/multiline`, then just send it as a multiline message.
- If we're running a command that doesn't support `draft/multiline`, such as `/part`, execute the lines one-by-one as normal messages? (Though if there's a mixture of supported and unsupported commands, this gets messey)
- Or simply reject multiline messages that use unsupported commands (but now, users cannot "execute many commands at once"; on non-`draft/multiline` networks I'm able to `/mode +b n!u@h <newline>/kick n` in one go)

---

- WeeChat version: 4.0.2
- OS, distribution and version: Debian 12 bookworm
- Terminal: [foot](https://codeberg.org/dnkl/foot/)
- Terminal multiplexer: tmux

**Comment by flashcode** [comment]
The problem here is that sending multiline message with parameters of a command, which is not designed for multiline support (like `/part`) results in unexpected behavior: in this case the second line is sent to the server, due to the way arguments are used in the `/part` command callback.

@trygveaa: I think we already discussed this or a similar issue, one solution would be that commands supporting multiline args advertise it explicitly. For example in Python:

```python
hook = weechat.hook_command("my_command", ...)
weechat.hook_set(hook, "multiline_parameters", "1")
```

And then if command does not support multiline, parameters are cut on first `\n`.

Example:

```
/part #test1
JOIN #test2
```

Then `/part` command callback would receive a single parameter `#test1` instead of these 2 parameters: `#test1\nJOIN` (`\n` being a real newline) and `#test2`.

**Comment by trygveaa** [comment]
Is it necessary with a setting on the command? Can't the IRC commands just be changed to only read up to the newline character? Or is it likely that this is a problem with commands from other places as well?

> Or simply reject multiline messages that use unsupported commands (but now, users cannot "execute many commands at once"; on non-draft/multiline networks I'm able to /mode +b n!u@h <newline>/kick n in one go)

You can use the `/input split_return` command to execute each line individually on multiline buffers (like it's done on non-multiline buffers).

**Comment by flashcode** [comment]
It could be done in each command callback, but it's a lot of work, I thought about a global way to solve it, as 99% of commands don't support multiline args today.

Even core commands and those added by s other plugins or scripts could have similar issue.

**Comment by trygveaa** [comment]
Ah, okay. Then explicitly setting that the command takes multiline parameters when creating the command is probably fine. It's a small breaking change for wee-slack, but that should be fine. It may affect other scripts as well, like wee-most, I haven't checked.

However, wee-slack uses some of the same commands as IRC, like `/msg`, `/topic`, `/join` and some more by using `hook_command_run`. Some of these accept multiline parameters. How will this work if we add a requirement for defining a command to be multiline? Or should wee-slack rather define these same commands as IRC with `hook_command` rather than using `hook_command_run`?

**Comment by flashcode** [comment]
Good catch, so my answers:

- yes it's a small breaking change, and I'm still not sure if it's the best solution, I'm thinking about an alternate solution, possibly by fixing only some irc command callbacks
- if you use hook_command_run, the callback would always receive exactly what you typed, as this hook doesn't even check the underlying command that would be executed if hook_command_run was not there: so the callback could receive multiline parameters even if for example the `/me` command doesn't support it; therefore the script adding hook_command_run would be responsible to parse correctly the parameters.

**Comment by flashcode** [comment]
Finally, I fixed the IRC plugin to not allow any multiline message except the real multiline messages (sent by the users).

So now if there is any newline in a command parameter that would be sent to function `irc_server_sendf()`, it is cut and everything after is ignored.

The result is that sending this only parts the channel, the `JOIN #test` is NOT sent and just ignored:

```
/part #test
JOIN #test
```

If this is working fine, I'll backport this on 4.0 branch.
