### ISSUE TITLE
/msg opens a new query buffer when echo-message is enabled

### ISSUE THREAD

**Issue by knolley** [weechat/weechat#2016]
## Bug summary
when echo-message is enabled, doing /msg opens a new private message buffer having my own user@host in the title (probably because it gets opened by receiving the message back)
/msg without echo-message doesn't open a new buffer and displays the outgoing message in the server buffer instead

## Steps to reproduce

1. enable echo-message
2. /msg nickserv help
3. observe new buffer

## Current behavior
/msg opens a buffer (with the wrong user@host in the title)

## Expected behavior
/msg shouldn't open a buffer, i should get something like '18:35 -- Msg(knolle) -> nickserv: help' in the server buffer instead

## Aditional Information
This does also mean that people doing /msg nickserv identify ${sec.data.securedpassword} as their .command get their plaintext password echoed back to them in a query buffer and logged
also applies when using /mute /msg

---

- WeeChat version: WeeChat 4.1.0-dev (git: v4.0.0-228-gc4c58e091)

**Comment by flashcode** [comment]
Hi,

This is not so easy to fix, I think the best approach would be to never open a query buffer if the received PRIVMSG comes from your self nick (if a query buffer already exists for the remote nick, it would be automatically used).

The only drawback of this is if you use weechat as an IRC relay client (for example with a remote WeeChat), and on the remote WeeChat you open a query with a nick, let's say `/query someone hello`. On the local weechat (relay client), this would not open a new buffer with `someone`.
But we could consider that if you use a relay client, this one should be used instead of the remote WeeChat / bouncer.

I thought about another solution by detecting that you did `/msg` on a nick, saving this, and later when the message is received, check if it was from `/msg`.
But that's not perfect, because some servers have different behavior on echo-message: for example ergo.chat sends back the PRIVMSG when you do `/msg nickserv help` while libera.chat doesn't send anything.

**Comment by flashcode** [comment]
I implemented my first proposal, now a message coming from self nick never opens a query buffer (but uses it if existing).

As I said, there's a side effect is you're connected to a bouncer, if needed I can add an option to always force a new query buffer, or to prevent the opening of the query buffer for some nicks.
