### ISSUE TITLE
cannot autoload several scripts in single command

### ISSUE THREAD

**Issue by lacygoill** [weechat/weechat#2018]
## Bug summary

`/script autoload` fails to autoload several scripts in a single command.

## Steps to reproduce

Run these shell commands:

    mv /tmp/test_weechat{,_moved}
    mkdir -p /tmp/test_weechat/python
    echo "import weechat ; weechat.register('aaa', '', '', '', '', '', '')" >/tmp/test_weechat/python/aaa.py
    echo "import weechat ; weechat.register('bbb', '', '', '', '', '', '')" >/tmp/test_weechat/python/bbb.py
    weechat --dir=/tmp/test_weechat --run-command='/script autoload aaa.py bbb.py'

`/quit` the WeeChat instance, and start a new one with the same `--dir`ectory:

    weechat --dir=/tmp/test_weechat

## Current behavior

Only `aaa.py` has been automatically loaded, which `/script list` confirms:

    │...     │ Scripts loaded:
    │...     │   ?     aaa.py  ()

And an error message has been printed in the core buffer for `bbb.py`:

    │... =!= │ python: script "/tmp/test_weechat/python/autoload/-a bbb.py" not found

## Expected behavior

Both `aaa.py` and `bbb.py` have been automatically loaded.  That is, `/script list` outputs:

    │...     │ Scripts loaded:
    │...     │   ?     aaa.py  ()
    │...     │   ?     bbb.py  ()

## Suggested solutions

N/A

## Additional information

N/A

---

   - WeeChat version: WeeChat 4.1.0-dev (git: v4.0.0-256-g91bb1ebf5) [compiled on Sep 20 2023 18:25:22]
   - OS, distribution and version: Ubuntu 20.04.6 LTS
   - Terminal: XTerm(353)
   - Terminal multiplexer (screen/tmux/…/none): none

**Comment by trygveaa** [comment]
Here's a single command to reproduce:

```
weechat -t -r '/set script.scripts.download_enabled on; /script install go.py grep.py; /wait 2 /script autoload go.py grep.py'
```

It looks to me like the issue is that the `<script>_script_autoload` signal is sent one time for each script, and that is in the format `-a <filename>`. But then the code at https://github.com/weechat/weechat/blob/91bb1ebf5d051a80cd0e9e2e0bce820f2fef0e3c/src/plugins/plugin-script.c#L1234-L1251 only looks for `-a` at the start of the string. So that block would have to be moved into the for loop below.
