### ISSUE TITLE
List of arguments in plugin/script API

### ISSUE THREAD

**Issue by 0xallie** [weechat/weechat#202]
It would be nice if the API would give you a list of arguments rather than expecting scripts and triggers to parse the string manually.

**Before:** `"#testchan testacc :test gecos"`
**After:** `["#testchan", "testacc", "test gecos"]`

This would be especially useful for getting the message from a `PRIVMSG` event in triggers. Syntax like `${arguments[0]}` would be nice, and either support negative indices or have an alias like `${text}` which is the part after the colon.

**Comment by flashcode** [comment]
Hi,

Since version 3.4, the IRC message parser now returns the number of command arguments parsed in "num_params", and each argument in "param1", "param2", etc. (taking care of ":" which marks the beginning of the last argument).

For example when you parse the message `:nick!user@host PRIVMSG #weechat :this is a test`, you'll have in output (all values in hashtable are string):

    num_params = "2"
    param1 = "#weechat"
    param2 = "this is a test"

See an example in the scripting guide: https://weechat.org/files/doc/weechat/devel/weechat_scripting.en.html#irc_message_parse

I think this answers to your need, so I close this issue.
