### ISSUE TITLE
color hashing change from 4.0 to 4.1

### ISSUE THREAD

**Issue by Ckath** [weechat/weechat#2032]
## Question
so I recently updated my stuff after not bothering for a while (4.0.4) and noticed after the update (4.1.0) that some nicks hash a different color, `Politik` for example.

my nick color hash settings have always been the same
```
nick_color_hash = djb2
nick_color_hash_salt = ""
```
(at least what I assume are the relevant ones):

this isnt a wide spread thing, only a couple if not just that one I'm noticing coming with a different color.
so my question here is is there some new config that could effect this? can I fix or correct it in any way? I'm very fond of my long term nick and color associations

---

- WeeChat version: 4.0.4 -> 4.1.0
- OS, distribution and version: arch

**Comment by flashcode** [comment]
Yes I confirm this was intentional, but it brings new issues that are not so easy to solve.

For now, I'm reverting the changes to compute in case sensitive way, as it was done in versions <= 4.0.x, and this will be released soon in version 4.1.1.

I don't close the door to reintroduce changes in future to compute in a case insensitive way, but this will be done differently.

**Comment by flashcode** [comment]
It's fixed on branches 4.1 and master, please try and report any issue.
