### ISSUE TITLE
Add an escape hatch for scripts to be able to print arbitrary ansi escapes

### ISSUE THREAD

**Issue by necauqua** [weechat/weechat#2058]
### Feature description

Well, basically I want #1364

But instead of worrying about terminal support, complex implementations, exposing it to users and whatnot, what I'm proposing is dead simple:

Allow something like `weechat.color('ansi')` to produce a symbol that will be rendered into `\x1B` or `\x1B[` - and then let scripts do whatever with it at their discretion :upside_down_face: 

Another usecase is custom terminal [links](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) - although here we need `\x1B]` - for example to convert ident'd hosts into mailto: links like thelounge does

**Comment by trygveaa** [comment]
This isn't possible to add support for with the current UI library that WeeChat uses, ncurses. It handles all text printing to the terminal and doesn't have a way to include an escape character in a text string. The reason for that is that it needs to understand the escape sequences in order to do text wrapping, side panels etc. If it would have been possible you would encounter issues such as color/links bleeding into the nicklist (when you have it on the right side as default).

It is possible to send escape sequences directly to the terminal, separately from any text in the UI though. This means you can't use it for colors or links, as the text for that would just appear where the cursor is, independently of any UI elements or the buffer you're in, and cleared when the UI is redrawn. But it can be used to e.g. send escape sequences for desktop notifications or with some limitations show images (either on top of the UI independently of it, or in the UI by using [unicode placeholders](https://sw.kovidgoyal.net/kitty/graphics-protocol/#unicode-placeholders)).

To send escape sequences directly to the terminal, just write directly to `/dev/tty`.
Here's an example in bash: https://gist.github.com/trygveaa/e304621f53c62c792864faeedfddb86b
And here's an example in a WeeChat Python script: https://github.com/trygveaa/weechat-icat/blob/ece458c6c17c00dab6fe5a7a4fc57c204d7a72b5/weechat_icat/terminal_graphics.py#L237-L240

**Comment by necauqua** [comment]
Ooh, I see, it seems like I did not quite realise what exactly the limitation was with ncurses, thanks for the detailed explanation.

Looks like best I could do atm is to coarse the #rrggbb into the 256-color palette, oh well

**Comment by trygveaa** [comment]
> Looks like best I could do atm is to coarse the #rrggbb into the 256-color palette, oh well

WeeChat already has a function for this btw. `color_rgb2term` in [info_get](https://weechat.org/files/doc/stable/weechat_plugin_api.en.html#_info_get).

**Comment by necauqua** [comment]
Oh, that's.. _significantly_ less code than what I've cooked up already, thanks again :)
