### ISSUE TITLE
screen garbled after switch/scroll  to a specific buffer line, Unicode-related

### ISSUE THREAD

**Issue by saper** [weechat/weechat#2130]
### Describe the bug

Switching the buffer and scrolling to a certain line containing Unicode sequence causes the display to go crazy, with the buffer contents overwriting the buflist and the like.

![after_scroll1](https://github.com/weechat/weechat/assets/248374/d5605bb0-904d-4fe5-a86b-2ab530fbdada)

### Steps to reproduce

I wasn't able to reproduce this reliably yet. I have tried to use empty buffer in an empty weechat and put some `/eval /print [<unicode>]` there but the problem could not be reproduced easily. (Thanks @flashcode for a very inspiring https://github.com/weechat/weechat/issues/1861 report how to try to reproduce. I am pretty new to WeeChat and I didn't know all those fancy commands)

### Current behavior

Out of 16 IRC buffers I have, switching to buffer number 3 and scrolling up to reach certain text causes part of the display mangled. In particular, timestamps from the buffer are scattered on the left hand side overlapping the buflist. Ctrl-L refreshes the screen, but the problem re-appears whenever I switch to the buffer again. Only one buffer is affected; I suspect there is something in the data weechat received that causes this.

### Expected behavior

Buflist and the rest of the screen refreshes reliably. 

### Suggested solutions

1. I tried to do some `/eval /print ...` tricks to reproduce this reliably on a clean session of weechat but I couldn't, at least not in a `/buffer add -free scratch` buffer.
2. Is there any additional troubleshooting information I can extract from the currently running session that exhibits that problem? (raw data, some debugging via `gdb`, ....) ?
3. Any hints to to try to reproduce this better?
4. Frankly I do not expect weechat developers to deal with every crazy unicode we might get. But no matter what we receive, there could have been some safeguards that make sure various parts of the user interface do not overwrite each other, even if one gets filled with junk.

### Additional information

Font used in rxvt-unicode [APL385](http://www.apl385.com/fonts/) does not support the Myanmar characters pasted. This may be an additional factor to cause the breakage.

`LANG` is set to `en_CA.UTF-8`
Some software version information:

```
$ rpm -qf /usr/bin/weechat
weechat-4.2.2-1.fc39.x86_64
$ ldd /usr/bin/weechat | grep ncurses
	libncursesw.so.6 => /lib64/libncursesw.so.6 (0x00007f67f9300000)
$ rpm -qf /lib64/libncursesw.so.6
ncurses-libs-6.4-7.20230520.fc39.1.x86_64
```

The screen from the bug report above after Ctrl-L refresh:
![after_refresh](https://github.com/weechat/weechat/assets/248374/a28fec88-bf09-445a-9f74-fa4823063f12)

Raw screen:

![raw](https://github.com/weechat/weechat/assets/248374/2540178a-2180-470e-abd9-097da9339e26)

The same screen session reattached under kitty with a different font that displays the characters show that  when we can display them, but the nicklist item gets moved to the left (the effect is slightly different to the rxvt-unicode terminal with APL385)

![kitty](https://github.com/weechat/weechat/assets/248374/0406feb1-bafc-4bd5-ac72-0e8da895098b)

Line with strange Unicode characters copied from the raw window:

```
00000000  31 31 3a 34 31 20 3c 6c  75 63 68 69 7a 3e 20 e1  |11:41 <luchiz> .|
00000010  80 99 e1 80 ba e1 80 b9  e1 80 82 e1 80 9c e1 80  |................|
00000020  ac e1 80 95 e1 80 ab 20  e1 80 81 e1 80 bb e1 80  |....... ........|
00000030  85 e1 80 ba e1 80 9e e1  80 b1 e1 80 ac 20 e1 80  |............. ..|
00000040  bb e1 80 ad e1 80 af e1  80 b8 20 e1 80 9e e1 80  |.......... .....|
00000050  ac e1 80 b8 e1 80 90 e1  80 ad e1 80 af e1 80 b7  |................|
00000060  e1 80 9b e1 80 b1 e1 81  8b 0a                    |..........|
0000006a
```

Unicode points decoded:

U+0031 U+0031 U+003A U+0034 U+0031 U+0020 U+003C U+006C U+0075 U+0063 U+0068 U+0069 U+007A U+003E U+0020 U+1019 U+103A U+1039 U+1002 U+101C U+102C U+1015 U+102B U+0020 U+1001 U+103B U+1005 U+103A U+101E U+1031 U+102C U+0020 U+103B U+102D U+1038 U+0020 U+101E U+102C U+1038 U+1010 U+102D U+102F U+1037 U+101B U+1031 U+104B

### WeeChat version

4.2.2

### What OS are you using?

Fedora release 39 (Thirty Nine)

### On which terminal are you running WeeChat?

rxvt-unicode-256color

### Which terminal multiplexer are you using?

screen

**Comment by flashcode** [comment]
Hi,

Most of times such display issues are not caused by WeeChat itself but wrong environment settings, like $TERM variable.

The TERM must have a proper value outside screen (before attaching), and inside (not the same).

You can look at this question in FAQ: https://weechat.org/files/doc/weechat/stable/weechat_faq.en.html#screen_weird_chars

Also you can try with another terminal and outside screen/tmux to check if it fixes the issue.

**Comment by saper** [comment]
Thanks, I have checked with kitty and rxvt-unicode, they behave a bit differently, but the garbling happens.

We need to find a way to reproduce this, so I can start new session and play with multiple terminals. Do you have any ideas how to do it? I tried to `/eval /print ...` this into an empty buffer but that does not do the trick. Could it be this is limited to IRC windows?

**Comment by trygveaa** [comment]
This seems like (mostly) a bug in screen. Two of the characters in the list of unicode points you provided are U+103A and U+1039. These are in the nonspacing mark category of unicode, which means they should be combined with the preceding character and not affect how wide the character is (how many terminal cells it occupies).

If you try to run `echo 'a\u103A\u1039b'` in a terminal emulator outside of screen you will see that the `b` is printed in the second cell which is correct. However, if you try to run it inside screen you will see that the `b` is printed in the first cell, so screen has considered the `a` together with the marks as having zero width.

The reason you can't reproduce it in an empty buffer might be that the buffer needs to have a nicklist for the bug to occur. Here's a way to reproduce it inside weechat when running in screen:

```
weechat -t -r '/server add libera irc.libera.chat -autoconnect -autojoin=#test-rendering; /wait 1 /eval /print -buffer irc.libera.#test-rendering ${\u103A}'
```

If you run it inside screen you'll see a lot of characters being stuck when switching between the buffers. If I run it without screen there's no stuck characters.

If I print all the characters you posted, I see a few characters being stuck on the line that's printed in some terminal emulators even without screen tough. That would be because the terminal emulator and weechat considers some of the characters to have a different width, but I haven't checked which characters this is. So that's why I said it's mostly a bug in screen, because there still might be some issues depending on which terminal emulator is used, but much less than inside screen.

Here's the command with all the characters if you want to test:

```
weechat -t -r '/server add libera irc.libera.chat -autoconnect -autojoin=#test-rendering; /wait 1 /eval /print -buffer irc.libera.#test-rendering ${\u0031\u0031\u003A\u0034\u0031\u0020\u003C\u006C\u0075\u0063\u0068\u0069\u007A\u003E\u0020\u1019\u103A\u1039\u1002\u101C\u102C\u1015\u102B\u0020\u1001\u103B\u1005\u103A\u101E\u1031\u102C\u0020\u103B\u102D\u1038\u0020\u101E\u102C\u1038\u1010\u102D\u102F\u1037\u101B\u1031\u104B}'
```

If you're not too tied to screen, I would personally recommend trying tmux instead, as it handles this much better.

**Comment by saper** [comment]
Fantastic answer, thank you very much! Will re-test and see. I had been using tmux for some time in the past, but somehow screen suits my taste better.

Will check if that can be fixed there.

**Comment by acidvegas** [comment]
setting your fonts or TERM will not do anything lol....this is an issue in how most modern terminals handle high level unicode rendering, esp when in a CURSES application.

A simple fix is clearing the screen and pressing `ALT+L` twice to redraw the display.
You can also switch to another buffer that doesnt have the unicode and do`ALT+L` twice to refresh it for a fix.

**Comment by trygveaa** [comment]
> A simple fix is clearing the screen and pressing `ALT+L` twice to redraw the display. You can also switch to another buffer that doesnt have the unicode and do`ALT+L` twice to refresh it for a fix.

Op already mentioned pressing ctrl+l (which is essentially the same as alt+l twice) as a temporary fix, but as they said it comes back when switching back to the problematic buffer.

> side note: using screen or tmux or some other terminal is not going to fix this.

Yes it may. Using a terminal emulator which handles character widths the same way as WeeChat will fix this. Using a multiplexer will likely not fix it, but may make the problem worse as demonstrated in my earlier comment.

side note: laughing at previous suggestions is not very nice.

**Comment by saper** [comment]
A one liner from @trygvea helped me to quickly narrow the problem down to the use of screen 4.9.1_2. tmux 3.3a_2 behaves correctly in this regard.

Unless someone believes there is something that weechat could do better, I would propose to close this bug. Thank you for your help, it was great to meet you (it was my first interaction here I believe).

**Comment by saper** [comment]
I could not reproduce the problem with the longer string either, tried in

alacritty-0.13.2_1
xterm-391
kitty-0.33.1_2
rxvt-unicode-9.31_1
weechat-4.3.0
ncurses from the FreeBSD base system, based on the  6.2-20210220 version. https://github.com/freebsd/freebsd-src/tree/fb623aab3927a6825ff7731198ec2e33426f7607/contrib/ncurses

**Comment by acidvegas** [comment]
> I could not reproduce the problem with the longer string either, tried in
> 
> alacritty-0.13.2_1 xterm-391 kitty-0.33.1_2 rxvt-unicode-9.31_1 weechat-4.3.0 ncurses from the FreeBSD base system, based on the 6.2-20210220 version. https://github.com/freebsd/freebsd-src/tree/fb623aab3927a6825ff7731198ec2e33426f7607/contrib/ncurses

the issue is, if you dont have certain fonts installed on your system, most high level unicode wont even render in the terminal how it should, but when you do have those fonts and the real unicode symbols show in the terminal, it renders in a very glitchy manner. when the lines are moving.
