### ISSUE TITLE
Integer Overflow to Buffer Overflow vulnerability in "string_free_split" functions

### ISSUE THREAD

**Issue by Crispy-fried-chicken** [weechat/weechat#2178]
### Question

Hi,
   we have detected that your project may be vulnerable to Integer Overflow to Buffer Overflow in the function of `string_free_split_shared `, `string_free_split`, `string_free_split_command` and `string_free_split_tags`  in the file of `src/core/core-string.c` . It shares similarities to a recent CVE disclosure [CVE-2024-6381](https://nvd.nist.gov/vuln/detail/CVE-2024-6381) in the [mongo-c-driver](https://github.com/mongodb/mongo-c-driver).

**The source vulnerability information is as follows:**

> Vulnerability Detail:
> CVE Identifier: CVE-2024-6381
> Description: The bson_strfreev function in the MongoDB C driver library may be susceptible to an integer overflow where the function will try to free memory at a negative offset. This may result in memory corruption. This issue affected libbson versions prior to 1.26.2
> Reference: https://nvd.nist.gov/vuln/detail/CVE-2024-6381
> Patch: https://github.com/mongodb/mongo-c-driver/commit/effd95c34ad421df94eec7c69236f0e4172552d0

Would you help to check if this bug is true? If it's true, I'd like to open a PR for that if necessary. Thank you for your effort and patience!

**Comment by flashcode** [comment]
Hi,

Thanks for the issue, I confirm there can be an integer overflow here, and at least these functions must be fixed (I'm checking if other functions could be affected as well).

Did you find this manually or automatically with a tool? If yes, which one?
I make regular scans of the source code for such issues, and it was not reported.

This issue should not really happen in practice, because INT_MAX is 2,147,483,647, so the integer overflow happens with this number of split items, that means with the separator between each item, the source string was at least 4,294,967,294 bytes long.

**Important note:** for any security issue found in WeeChat (even if you're not sure it's one), please do not post in the public tracker, see file [CONTRIBUTING.md](https://github.com/weechat/weechat/blob/master/CONTRIBUTING.md#security-reports).
This allows time to properly fix the issue in all versions, then announce the vulnerability publicly. Thanks!

**Comment by flashcode** [comment]
No e-mail needed, we can go on here, as this has a minor impact on users (should not happen in practice).

Yes, a fix is welcome.
I see in mongodb they just use a pointer without index variable (https://github.com/mongodb/mongo-c-driver/pull/1552), which is fine to me.

**Comment by flashcode** [comment]
> Hi, I've already open a pr for it, which is #2179. Please review it.

Thanks.

> Besides, is there need to backport it to the branch 4.4 and 4.3?

Yes, I'll do it myself once this is merged in master branch. At least on branch 4.4.

**Comment by flashcode** [comment]
> Thanks, and is there any need to request a CVEID for this vulnerability due to the potential affects on your weechat?

It's better to have one yes, and I'll link it on the security page: https://weechat.org/doc/weechat/security/

But please wait a bit so I can investigate if other functions are affected and require a similar fix.

**Comment by flashcode** [comment]
I found the same problem in other functions, I'm fixing them all.

Does your tool detect them?
I would be interested by such tool, or a similar one, to catch such issues during the development.
Is GitHub CodeQL (used in this project) able to detect such issues?

**Comment by flashcode** [comment]
I fixed similar problems and backported everything on branch 4.4.

I'll release version 4.4.2 after some tests.

**Comment by flashcode** [comment]
I also added the vulnerability in the list: https://weechat.org/doc/weechat/security/WSA-2024-1/

**Comment by flashcode** [comment]
Yes, I'm requesting one and I'll add it in the list and in the ChangeLog once attributed.
