### ISSUE TITLE
Support SSH key authentication for relay connections

### ISSUE THREAD

**Issue by GMDSantana** [weechat/weechat#2212]
### Feature description

I would like to suggest a feature enhancement for WeeChat's relay functionality. Currently, when connecting to a WeeChat relay server, it is necessary to either to setup an SSH tunnel, or enter a password for authentication. While this works, it would be more secure and convenient to natively allow SSH key authentication as an option.

**Comment by flashcode** [comment]
Hi,

I suppose your are talking about the "weechat" relay, which is a custom protocol in WeeChat.
This relay has been superseded by "api" relay, which is a standard HTTP REST API, see the doc here: https://weechat.org/files/doc/weechat/devel/weechat_relay_api.en.html
For now the only known client is WeeChat itself (you can connect from WeeChat to another WeeChat using api relay).

There should be no more evolutions on the weechat relay, that could be removed in future.

And for HTTP authentication, I think it doesn't make sense to authenticate with a SSH key, as this is has nothing to do with a SSH server.

**Comment by GMDSantana** [comment]
Hi, @flashcode . Thanks for your reply and for the amazing work with WeeChat. ^^

That makes sense, I understand now. But after reading the documentation, it looks like it's also based on passwords and hashed passwords, right?

If that's the case, would it be possible to implement client-side certificate authentication (Mutual TLS) for the API relay? This would allow for secure passwordless connections in HTTPS. Another suggestion for passwordless authentication would be to support token-based authentication for the API relay if possible.

**Comment by mhoran** [comment]
I’ve been thinking a bit about what moving to the new API relay will mean for weechat-android and weechatRN. In weechat-android we support many different connection methods: TCP, TLS, and WebSocket, all terminated by WeeChat directly, and then SSH, which creates a local tunnel to WeeChat over TCP. I think we can still support SSH with the new API relay, just that instead of tunneling a TCP connection to WeeChat, we would tunnel the WebSocket connection.

Similarly, for Mutual TLS, one could implement this in a proxy server in front of WeeChat. Of course, this would also require relay clients to implement the same. But I do not think that these connection mechanisms need to be implemented in WeeChat itself; just a fronting server and the relay clients.

Personally, having maintained weechat-android for many years and dealt with the issues we have had with the various connection types, I think having fewer is better than many. In weechatRN I only support WebSockets, and that has significantly reduced the maintenance burden.

**Comment by GMDSantana** [comment]
> I’ve been thinking a bit about what moving to the new API relay will mean for weechat-android and weechatRN. In weechat-android we support many different connection methods: TCP, TLS, and WebSocket, all terminated by WeeChat directly, and then SSH, which creates a local tunnel to WeeChat over TCP. I think we can still support SSH with the new API relay, just that instead of tunneling a TCP connection to WeeChat, we would tunnel the WebSocket connection.
> 
> Similarly, for Mutual TLS, one could implement this in a proxy server in front of WeeChat. Of course, this would also require relay clients to implement the same. But I do not think that these connection mechanisms need to be implemented in WeeChat itself; just a fronting server and the relay clients.
> 
> Personally, having maintained weechat-android for many years and dealt with the issues we have had with the various connection types, I think having fewer is better than many. In weechatRN I only support WebSockets, and that has significantly reduced the maintenance burden.

Hi, @mhoran . Thanks a million for the feedback. ^^ It makes all the sense, I fully agree that the balance between adding new features and keeping maintenance manageable is important. I think passwordless authentication would be great, but if maintenance would be an issue here, I am happy with the current workarounds.
