### ISSUE TITLE
/set weechat.bar.input.items default takes it as "default" and makes the input bar invisible

### ISSUE THREAD

**Issue by ninja-coding** [weechat/weechat#343]
I'm not 100% sure if this is a bug or not but since I didn't type default with quotes I expected it to restore the input prompt to the default values instead it took default as a string and made the input bar invisible:

![Image of bug](https://i.imgur.com/LaZ8NLM.png)

**Comment by flashcode** [comment]
Not really a bug, but something that WeeChat lets you do, and that could be problematic.
You can change items in bars, reorder them, hide bars, ... which can be a problem with input bar: you don't see what you type any more.
If you want to restore the default input bar, just delete the bar, WeeChat will create it again because an input item is required: `/bar del input`.

It would be possible to add extra controls if you change items in bar, if you hide the bar, ... but it will require some code maybe not needed (it's rare to change items in input bar).
