### ISSUE TITLE
/connect tries to start a local server

### ISSUE THREAD

**Issue by paperdigits** [weechat/weechat#374]
Hello, 

I'm using weechat 1.1.1 on Arch Linux, both x86_64 and ARM. When trying to connect to a server that hasn't been added using /server add ... weechat tries to create a local server, then gives up:

04:28:53 =!= | irc: unable to create temporary server "irc.geekshed.net" because the creation of temporary servers with command /connect is currently disabled
04:28:53 =!= | irc: if you want to create a standard server, use the command "/server add" (see /help server); if you really want to create a temporary server (NOT
             | SAVED), turn on the option irc.look.temporary_servers

When I add the server, then /connect alias, it connects.

**Comment by flashcode** [comment]
Hi,
Since version 1.1, you can not create and connect to a server directly with command `/connect`, because this is not the recommended way to add and connect to servers (it's recommended to `/server add` it, then `/connect`).
But as you can see in the error displayed, there's a way to enable that again if you really want the feature back, you can do `/set irc.look.temporary_servers on`.

**Comment by paperdigits** [comment]
Oh well, silly me! Thank you for your timely reply.
