### ISSUE TITLE
autosetbuffer on title property only works for private buffers

### ISSUE THREAD

**Issue by pascalpoitras** [weechat/weechat#462]
I typed /autosetbuffer add irc.bitlbee.&facebook title Facebook
Then I restarted weechat but the &facebook channel has no title at all.
I also do the same for an exec buffer /autosetbuffer add exec.exec.conky title Conky - the light-weight system monitor
Then I restarted weechat, typed /exec -norc -buffer conky "true"
But the title is still "Executed commands"
However I Have no problem when I use autosetbuffer title on a private buffer.
The only way to change the title of the &facebook and exec buffers is by doing it manually everytime /buffer set title Facebook

**Comment by flashcode** [comment]
Hi,
This is an issue with the script: the script sets the title (on signal "buffer_opened"), but then WeeChat sets the title again after.
So the script could be fixed to introduce a very small timer between the signal and the set of buffer properties.
Please open a new issue in weechat/scripts repository, since it's not a WeeChat problem.

**Comment by Mikaela** [comment]
>  Please open a new issue in weechat/scripts repository, since it's not a WeeChat problem.

And `@ping` the author as they aren't following the repo?

**Comment by flashcode** [comment]
The author is me, so it will not be a problem for this script ;)
