### ISSUE TITLE
User confirmation for /upgrade, /quit, ...

### ISSUE THREAD

**Issue by azrdev** [weechat/weechat#463]
I'd like to have a manual confirmation for "destructive" commands such as `/upgrade` or `/quit`, so as not to accidentally dis/re-connect all buffers.

**Comment by flashcode** [comment]
For `/quit` you can set this option: `/set weechat.look.confirm_quit on`.
The `/upgrade` should not "destroy" anything (except that you're disconnected and automatically reconnected to IRC servers, but only if you use SSL).

**Comment by Mikaela** [comment]
> if set, /quit command must be confirmed with extra argument "-yes" (see /help quit)

and when I accidentally scroll commands up with the up key and happen to hit enter when it says `/quit -yes`... What happens?

**Comment by flashcode** [comment]
@Mikaela: this should never happen, if you recall a command which is `/quit -yes`, this would have quit WeeChat. The only case is if you type `/quit -yes` but don't execute it and save it in history. But if you recall that and press Enter, you know what you do.
For me it doesn't make sense to add extra confirmations on `/quit` (otherwise it would be very annoying).
I'll add similar behavior for `/upgrade`.

**Comment by Mikaela** [comment]
I think optimal behaviour would be having the same as what happens when you attempt pasting multiple lines by default "Are you sure that you wish to quit/upgrade/whatever [y/N]".

**Comment by Shawn-Smith** [comment]
I think /upgrade should also have a `-yes` option, but other than that it's fine as it is.

>and when I accidentally scroll commands up with the up key and happen to hit enter when it says /quit -yes... What happens?

That's just needless hand-holding.
