### ISSUE TITLE
weechat-1.2/src/plugins/python/weechat-python.c:1067: use after free ?

### ISSUE THREAD

**Issue by dcb314** [weechat/weechat#486]
weechat-1.2/src/plugins/python/weechat-python.c:1067]: (error) Returning/dereferencing 'python2_bin' after it is deallocated / released

        if (python2_bin && (strcmp (python2_bin, "python") != 0))
        {
            rc = stat (python2_bin, &stat_buf);
            if ((rc != 0) || (!S_ISREG(stat_buf.st_mode)))
            {
                free (python2_bin);
                weechat_python_set_python2_bin ();
            }
        }
        return python2_bin;

**Comment by flashcode** [comment]
Hi,

Which tool does return this warning/error?

For me the code is OK, the function weechat_python_set_python2_bin() should always set `python2_bin` to a non-NULL value (and it's initialized to NULL at the beginning).
But I can adapt the code to remove this warning, for example by returning the value instead of setting it (in weechat_python_set_python2_bin), this would give for example:

    if (python2_bin && (strcmp (python2_bin, "python") != 0))
    {
        rc = stat (python2_bin, &stat_buf);
        if ((rc != 0) || (!S_ISREG(stat_buf.st_mode)))
        {
            free (python2_bin);
            python2_bin = weechat_python_get_python2_bin ();
        }
    }
    return python2_bin;

**Comment by dcb314** [comment]
>Which tool does return this warning/error?

A static analyser called cppcheck, available from sourceforge.
