### ISSUE TITLE
Passive DCC

### ISSUE THREAD

**Issue by michaelkebe** [weechat/weechat#487]
Currently weechat only allows "active" DCC.
I have found a request on the old savannah nongnu project page, but nowhere else.
So I create a new one here on github.

http://savannah.nongnu.org/task/?5572

**Comment by hasB4K** [comment]
That would be a great enhancement!

**Comment by johnem-msft** [comment]
I feel like if we could set options in xfer.conf for incoming DCC connections we could fix this, as one could then go ahead and perform port forwarding on said ports to the affected client from a local router forwarding needed ports for passive connections ... (or am I not understanding the whole issue?)

Currently - xfer.conf has a single setting for: xfer.network.port_range  (port_range = "") - but adding a port range here is not helpful for this attempted workaround as the setting appears to be for outgoing connections only.
Here https://weechat.org/files/doc/stable/weechat_user.en.html#xfer_options  the user guide mentions: 
"xfer.network.port_range
description: restricts *outgoing* files/chats to use only ports in the given range (useful for NAT) (syntax: a single port, ie. 5000 or a port range, ie. 5000-5015, empty value means any port, it's recommended to use ports greater than 1024, because only root can use ports below 1024)"

Eg. on other clients we can limit the DCC Ports used to 5000-5015 for example, and then go into a router and port forward those ports ... but this setting appears to be only for outgoing - can we get an all-inclusive setting or a setting for incoming eg. port_range_incoming?

**Comment by eimann** [comment]
This would still not enable passive DCC, because it is based on token or key (reverse) negotiation, fserve, rdcc, reverse or dcc server.

**Comment by andrewstec** [comment]
I'd like to also request an incoming passive DCC feature. We would need the incoming port range for the router to match the ports with plus the reverse negotiation that @eimann mentioned probably. I'm not familiar with the negotiation on passive DCC receiving though.

**Comment by stefan1983** [comment]
+1

**Comment by flashcode** [comment]
Implemented via PR #2004.
