### ISSUE TITLE
Problem with character encoding

### ISSUE THREAD

**Issue by debian07** [weechat/weechat#499]
Hello. I connect to a server that uses "ISO-8859-15" charset. In older releases I uset the command "/charset ISO-8859-15" to configure it, and it worked without problems. Yesterday I upgraded weechat to version 1.3 and I can't see anymore special characters on that server. I checked the configuration and nothing changed. I tried to set again the ISO-8859-15 charset but nothing happens. I use weechat 1.3 on OSX 10.10.5 with iTerm, and was installed with brew following the official documentation. At this time I can't check if this also happens on the Linux version.

**Comment by flashcode** [comment]
Hi,

Please check the release notes here, a new option has been introduced for channel names encoding: https://weechat.org/files/releasenotes/ReleaseNotes-1.3.html
If your problem is fixed with this option enabled, I'll close this issue.

Note: I recommend to use UTF-8 everywhere, it's far better than ISO (more chars supported, should work better everywhere, especially in WeeChat where everything is stored as UTF-8 internally).
Of course I can understand if you have really no choice and must use ISO, that's why I introduced a new option to bring back the old behavior (which had bugs too, see the issues: #482, #218).

**Comment by debian07** [comment]
Hi. Enabling the new option I can see special characters again. Sorry, I didn't know about this new option. Thank you very much for your help ^^

**Comment by flashcode** [comment]
OK, good to know the new option fixes your problem.
