### ISSUE TITLE
Alt-Backspace should eat less than Ctrl-W

### ISSUE THREAD

**Issue by purpleidea** [weechat/weechat#559]
In pretty much every terminal environment I know, including bash and irssi, pressing alt-backspace eats one word at a time. For example:

```
word1.word2-word3_word4
```

Would get "eaten" by four repeated presses. Unfortunately, in weechat, all four disappear with a single stroke. The 1.2 release notes allude to this being configurable:

`"- add options to customize word chars (for detecting word boundaries)"` from https://weechat.org/news/87/20150510-Version-1.2/

but if that's the case, I haven't figured out how. I'd like to request this functionality, and if it is available and someone can explain how to enable it, then perhaps a docs patch is in order.

Thanks in advance!

**Comment by flashcode** [comment]
Hi,

Yes, since WeeChat 1.2, you can customize the word chars, and by default with your example the key Ctrl-W should remove the three last words, then the first one. Which is not exactly what you want.
If you want to consider that `-` and `_` are NOT part of words, then you can do:

    /set weechat.look.word_chars_input  "!\u00A0,|,alnum"

Then Ctrl-W should delete words one by one.

**Comment by purpleidea** [comment]
@flashcode Thanks for the response however, Ctrl-W should delete the whole chunk, where as alt-backspace should delete one word at a time.

Is there a way to set this behaviour?

**Comment by flashcode** [comment]
No, in WeeChat Ctrl-W and Alt-backspace are bound on same command. And there's only one command to remove the previous word, so no way to have a different behavior for both keys.

**Comment by flashcode** [comment]
I just tried in bash, and I see the difference. Then I turn this issue as an feature request, to introduce different behavior between Ctrl-W and Alt-backspace.

**Comment by purpleidea** [comment]
On Fri, Oct 23, 2015 at 1:51 AM, Sébastien Helleu <notifications@github.com>
wrote:

> I just tried in bash, and I see the difference. Then I turn this issue as
> an feature request, to introduce different behavior between Ctrl-W and
> Alt-backspace.



Much appreciated thanks. Maybe you can steal the necessary code from irssi
:)

Cheers!

**Comment by flashcode** [comment]
Stealing code is not an option for me ;)

**Comment by purpleidea** [comment]
@flashcode Come disait Picasso: "Good artists copy, great artists steal."

Les licenses sont compatible :)

**Comment by andreaskern** [comment]
Ctrl-W should delete to the previous whitespace
Meta-Del should delete to the previous word boundary

this is the default behavior in irssi and GNU readline (which is used by bash and others)

here is the **irssi** code [source](https://github.com/irssi/irssi/blob/50775e92e64561837e6c805fc8fef19aedaafeb4/src/fe-text/gui-readline.c#L1049)

	key_bind("delete_previous_word", "Delete the word before the cursor", "meta-backspace", NULL, (SIGNAL_FUNC) key_delete_previous_word);
	key_bind("delete_to_previous_space", "Delete up to the previous space", "^W", NULL, (SIGNAL_FUNC) key_delete_to_previous_space);

but the function definitions rely on c++ features in the code, so no easy copy and paste there

in **GNU readline** the function is [`rl_backward_kill_word`](http://git.savannah.gnu.org/cgit/readline.git/tree/kill.c#n225)
which uses `rl_backward_word`, which uses the  `iswalnum` function and additionally accepts these characters `/-_=~.#` because they can appear in pathnames. [source](http://git.savannah.gnu.org/cgit/readline.git/tree/util.c#n69)

and the documentation says

    C-w
        Kill from the cursor to the previous whitespace. This is different than M-DEL because the word boundaries differ.

My Problem was, that C-w did not delete enough (only til the previous dot). To fix the C-w behavior I use 

    /set weechat.look.word_chars_input  "!\u00A0,/,-,_,=,~,.,#,|,alnum"

**Comment by Apteryks** [comment]
Hello!

I was thinking: Is there a reason Weechat can't use GNU Readline directly instead of reinventing the wheel (incompletely) ?  There are still things I'd expect to work, which don't, e.g.:

1. Alt-Backspace should delete the word, 
2. Alt-u should uppercase the word
3. Alt-l should lowercase the word
4. Ctrl-s should search forward in history
5. Ctrl-r should search backward in history

I'm probably forgetting a bunch of muscle memory shortcuts I'm used typing in Bash in a terminal emulator (or in Emacs).  GNU Readline is good and battle tested; I think it'd be nice to use it, so that common users expectations (e.g. learned rom their interactions at a Bash shell) are met.

**Comment by flashcode** [comment]
Hi @Apteryks,

GNU Readline is not used because it would be complicated to migrate now, considering the existing code and the way weechat handles keys.

However, I'm working to add new keys to capitalize of upper/lower words in input.
Search in input can be done with a script: `/script install histsearch.py`

Since the commit 01cf98e8fbd8411464fcedd97d7400d961f7e1f5, alt+backspace now deletes one word while ctrl+w deletes until previous whitespace, the default bindings are:

```
meta-backspace /input delete_previous_word
ctrl-w /input delete_previous_word_whitespace
```

And the delimiter chars can be configured via the option `weechat.look.word_chars_input`.

**Comment by Apteryks** [comment]
Hi, OK, good to know Weechat will grow some of the GNU Readline features I've grown to take for granted; thanks for working on it!
