### ISSUE TITLE
short_name with go.py script

### ISSUE THREAD

**Issue by axionix** [weechat/weechat#574]
If I set core.weechat's short_name to "core", and then i set freenode.#weechat's to "weechat", go cannot even find the new weechat to jump to. Not sure whether to file this under weechat or the plugin.

**Comment by flashcode** [comment]
I tried and had no problem.
If you still have the problem, please give me the WeeChat version used, the OS (and its version), and the exact steps (commands) to reproduce the problem with a default config (for example with `weechat --dir /tmp/weechat`).
And if the problem is only with the script go.py, the issue should be opened in scripts git repository.

**Comment by axionix** [comment]
I reproduced the issue with a blank config, using WeeChat 1.3 using the Arch Linux package.

To reproduce, you need to set:
plugins.var.python.go.short_name = "on"
plugins.var.python.go.use_core_instead_weechat = "on"

It then mistakenly renames the weechat channel buffer to core as well.

**Comment by weechatter** [comment]
Problem is the name of short_name "weechat" instead of "#weechat", but the core buffer itself is called "weechat". Its not a good idea to relabel a buffer with an name that is already in use.

@Flascode: "/buffer set short_name" should check if the name is already in use.

**Comment by flashcode** [comment]
@weechatter: it's possible to use same short name on different buffers, because the short name was designed to be used only for display (not to search buffers, like go.py does).
So if I'm more strict on that, it could annoy other people (using same short name on different buffers).

**Comment by weechatter** [comment]
Ok. Then i don't submit a patch for weechat and i am going to improve go.py
