### ISSUE TITLE
Handle IRC message 437

### ISSUE THREAD

**Issue by torhve** [weechat/weechat#62]
WeeChat does not join channels that are unavailable at startup

**Comment by flashcode** [comment]
Hi,

Issue #88 has been fixed (not exactly the same issue though).

Now I'm not sure what could be done for this issue, when WeeChat connects to a server with a nick banned on channel, the following message is displayed in server buffer:

    -- | #test: Cannot join channel (+b)

And when the option `irc.look.buffer_open_before_autojoin` in `on` (default value), the channel buffer is open, but remains empty (not joined), because of the ban.

I think nothing can be done on WeeChat side to prevent this, so I close this issue.
Feel free to comment if you have ideas about what to do differently.
