### ISSUE TITLE
logger.file.mask does not interpret '$server' and '$channel' for core logging when value starts with a date format such as '%Y'

### ISSUE THREAD

**Issue by atoponce** [weechat/weechat#647]
WeeChat version 1.3 on Debian Sid.

If `logger.file.mask` is set to `%Y/$plugin/$server/$channel/%Y-%m-%d.log`, then the following directory tree is created (assuming 2016 year):

    $ tree
    .
    └── 2016
        ├── core
        │   └── $server
        │       └── $channel
        │           └── 2016-01-06.log
        └── python
            └── $server
                └── $channel
                    └── 2016-01-06.log

Instead, it seems that it should be:

    $ tree
    .
    └── 2016
        ├── core
        │   └── weechat
        │       └── 2016-01-06.log
        └── python
            └── weechat
                └── 2016-01-06.log

If `logger.file.mask` does not start with a date format, then `$server` and `$channel` are interpreted correctly.

**Comment by flashcode** [comment]
This is not a bug, local variables `$server` and `$channel` are relevant only for IRC plugin (and maybe some external other plugins), but not for core buffer.
That's why you can create masks by plugins, for example a mask for irc. Please look at user's guide here, there's an example for irc plugin: https://weechat.org/files/doc/devel/weechat_user.en.html#logger_filenames_masks

That means in option `logger.file.mask` you can use only local variables `$plugin` and `$name` and in masks specific to plugins, you can use extra local variables (tip: you can see buffer local variables with `/buffer localvar`).

**Comment by atoponce** [comment]
So how does it work when the setting does not start with "%Y"?

**Comment by flashcode** [comment]
As expected, it does not work for me, even if the value does not start with `%Y`.
If you know a value where `$server` and `$channel` is working for core buffer, please let me know, I'll try.
