### ISSUE TITLE
Remove dark blue nick color

### ISSUE THREAD

**Issue by klloe** [weechat/weechat#788]
I can't see the dark blue colored nicks. Would you consider to remove them from weechat? I don't need any glasses but it is impossible to see that color. I think weechat would do a great job with being accessible for all its users!

![rtmcx4l](https://cloud.githubusercontent.com/assets/1057526/18056974/6db6b5b2-6e0e-11e6-9c50-95a2ccfd8556.png)

**Comment by Mikaela** [comment]
You can disable those colours by yourself. See `/help weechat.color.chat_nick_colors`.

@flashcode What does the enchancement label mean for this issue? That the colour will be removed and people with different terminal background colour will have issue?

**Comment by flashcode** [comment]
@Mikaela yes the blue could be removed from default config, if that's an issue for many users. I know this can easily be changed, but working config out of the box is better.
This could be discussed, because removing a color from the list would change all nick colors.

By the way some other options are blue by default, like the null values for options (displayed by /set).

**Comment by Mikaela** [comment]
@flashcode What about white terminal backgrounds which GNOME/MATE and possibly also OS X terminal default to?

This issue seems to be moving the issue from X people to Y people.

**Comment by flashcode** [comment]
Yes removing this color may not be a good idea for everybody.
So the solution is maybe to do nothing :D

**Comment by yrmvgh** [comment]
I think the greater issue is that, by default, many terminals have colors which don't show up well on their own default background color. For folks with poor eyesight that can be incredibly annoying. While I wish it could, I don't think weechat can solve the issue from its end. It would have to identify the terminal's color set and then ban colors which are too close in value somehow.

**Comment by nnathan** [comment]
I have been frustrated with this issue for months, even removing the "blue" colour from the nick colour list, only to see it to continue show up. Well it turns out lightblue and blue on my terminal are indistinguishable!

Took me quite awhile to realise that instead of fighting weechat you can simply adjust the ANSI colours in the settings of your terminal emulator. I'm pretty certain this is configurable with any modern terminal emulator.

Anyway just wanted to point that out incase people came here frustrated being unable to see blue (or brown) in their terminal.
