### ISSUE TITLE
weechat uses libc's wcswidth

### ISSUE THREAD

**Issue by ghost** [weechat/weechat#79]
Weechat uses the libc's wcswidth, which is implemented in terms of the libc's wcwidth, typically. Unfortunately, glibc's wcwidth is rather out of date and therefore untrustworthy. weechat should, instead, [import mgk25's wcwidth/wcswidth implementations](http://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c). I believe this will permit weechat to support Unicode more correctly.

**Comment by flashcode** [comment]
Here's a post with a workaround: https://blog.nytsoi.net/2015/05/04/emoji-support-for-weechat

**Comment by Aerdan** [comment]
Yup, but that's basically just externalizing the workaround I opened this bug to offer.

**Comment by kaniini** [comment]
It should be fixed in glibc.  Overriding `wcswidth` (or any other libc symbol) is undefined behaviour and otherwise creates unnecessary maintenance burden.

**Comment by Mikaela** [comment]
I believe this is fixed in glibc, but too recent glibc to be in any distribution yet, or maybe it's in Arch.

**Comment by kyrias** [comment]
It was committed after the 2.21 release, but should be fixed in the next one.

**Comment by Earnestly** [comment]
This is fixed in glibc.

Don't blame glibc versions, blame your distro for using outdated versions.  I've been running glibc from git for awhile without issue.  Most distributions are just bad and insecure.

As an addendum, weechat did the right thing here.  It should never have used its own implementation of wcwidth, this is distinctly the job of the libc and should be fixed there (which it was).  Many thanks to Alexandre Oliva and Mike FABIAN for this work.

![trains](https://ptpb.pw/EgTm.png)

**Comment by flashcode** [comment]
@Earnestly: not really related, but maybe you have an idea for this problem? https://github.com/weechat/weechat/issues/258#issuecomment-137933917

**Comment by dustymabe** [comment]
For some reason I'm having issues getting emojis to display in weechat. I'm running on fedora which has a recent glibc:

```
[user@2292af9c798e ~]$ rpm -q weechat glibc google-noto-emoji-color-fonts
weechat-2.2-1.fc29.x86_64
glibc-2.28-26.fc29.x86_64
```

is it required for me to grab one of the [weechat emoji plugins](https://weechat.org/scripts/stable/tag/emoji/) to get this to work?

**Comment by weechatter** [comment]
none of the weechat emoji scripts will fix display bugs. Maybe its a font issue

**Comment by dustymabe** [comment]
> none of the weechat emoji scripts will fix display bugs. Maybe its a font issue

thanks. it seems to be working now (not sure what changed since yesterday). emojis are showing up in IRC. The only issue I have now is that emojis aren't showing up in slack (weeslack plugin). I'll see if I can figure out what is going on there.

Thanks again @weechatter

**Comment by trygveaa** [comment]
@dustymabe, @birdayz: wee-slack doesn't show emojis, only text representations (like `:smile:`), because that's what it receives from the server. It's on my (long) todo list to implement some translation, but not sure when I'll get it done. If you have any issues, feel free to open an issue in https://github.com/wee-slack/wee-slack.

**Comment by dustymabe** [comment]
> It's on my (long) todo list to implement some translation

thanks @trygveaa! Is there an issue we can subscribe to to follow the progress of that feature?

**Comment by trygveaa** [comment]
@dustymabe: https://github.com/wee-slack/wee-slack/issues/465
