### ISSUE TITLE
WeeChat states that a Diffie-Hellman key exchange was performed, but it wasn't

### ISSUE THREAD

**Issue by aaronmdjones** [weechat/weechat#857]
Hello. When connecting to a network with TLS, the client outputs:

` --- │ gnutls: connected using 3072-bit Diffie-Hellman shared secret exchange`

Yet, a packet dump and a `/WHOIS` both confirm that an ECDHE- cipher suite was negotiated, which does not use that.

This is on version `1.7-dev (git: v1.6-37-g01f8443)`.

**Comment by welwood08** [comment]
The "DH" in ECDHE stands for Diffie-Hellman - are you sure your conclusion is correct?

**Comment by aaronmdjones** [comment]
I am.

The `3072` value is from `irc.network.foo.ssl_dhkey_size`, which WeeChat unconditionally grabs here: https://github.com/weechat/weechat/blob/master/src/plugins/irc/irc-server.c#L4094-L4098

That value is only used for classical DH, and as you can see, WeeChat prints that text unconditionally (i.e. for any type of key exchange).

Further, the largest ECDH curve I know of is only 571 bits, a far cry short of the 3072 quoted.

**Comment by welwood08** [comment]
Oh I see, of course. I had homed in the Diffie-Hellman aspect rather than the number of bits being impossibly high for EC - maye that could be clarified in the title.

Agreed that printing that message unconditionally does seem to be a problem - it also seems possible to connect with plain RSA without DH and still receive that message (although I haven't tested because WeeChat is currently non-functional for me due to a separate issue).

I would go so far as to say the displayed number could be incorrect even when "classical" DH key exchange has been used because the client-side number is just to set the minimum that GnuTLS will accept. The user's preference says nothing about what the server decided to use other than it was at least that many bits given that the connection has succeeded at this point.

Digging a bit, it seems the correct way to do this is to use `gnutls_dh_get_prime_bits` to find the actual number of bits used by a given session, and maybe not print the message if it returns 0 etc.

**Comment by aaronmdjones** [comment]
Exactly. :)

**Comment by welwood08** [comment]
Now that I'm able to connect to servers with WeeChat, I can also confirm my suspicion about connecting without DH:
```
Option changed: irc.server.test.ssl_dhkey_size = 2047483647
Option changed: irc.server.test.ssl_priorities = "NORMAL:!DHE-RSA:!DHE-DSS"
[snip]
gnutls: connected using 2047483647-bit Diffie-Hellman shared secret exchange
[snip]
<server>: *** You are connected to <server> with TLSv1.2-AES256-GCM-SHA384-256bits
```

**Comment by aaronmdjones** [comment]
Laugh at that key size.
