### ISSUE TITLE
Add ssh-tunnel for proxy

### ISSUE THREAD

**Issue by Salvati0n** [weechat/weechat#926]
Looking for the ability to use an ssh-tunnel to connect to an irc server from one shell box to another. Just have to add a username password and port and weechat will create the tunnel to connect to the irc server. I believe something like this is already done for the android app.

**Comment by stfnm** [comment]
Isn't that already possible? You create the tunnel with ssh -D and use it as socks5 proxy in weechat.

**Comment by mgedmin** [comment]
I use an SSH tunnel to connect to my ZNC instance (because I'm paranoid and don't want ZNC exposed to the Internet).  Whenever I suspend and resume my laptop, weechat tries to reconnect to localhost:6667 and fails.  I have to re-run my shell script to re-establish the SSH tunnel, and then kick weechat into reconnecting (or wait until weechat decides to retry).

Life would be easier if weechat could reestablish the tunnel before reconnecting.  An option to run a shell command before that would be sufficient.
