### ISSUE TITLE
buflist: fg color for current buffer is not applied

### ISSUE THREAD

**Issue by wdbw** [weechat/weechat#954]
The foreground color specified in `buflist.format.buffer_current` (_lightgreen_ by default) is ignored or overridden by some other setting.

This is on version `1.8-dev (git: v1.7-147-g084f9d7b5)`.

**Comment by squigglezworth** [comment]
I believe the issue is, by default, the buffer_current setting uses format_buffer, which then uses color_hotlist to color the buffer name. This overrides any color settings in buffer_current.

**Comment by therockmandolinist** [comment]
Is this resolved? I'm still seeing this issue

**Comment by flashcode** [comment]
This is not really "resolved", but now there's no default foreground color any more in the format for current buffer. This is because this foreground color is overriden by other colors like hotlist (not a bug, it's like that by design).
So if you want to use foreground color in the format of current buffer, you must change the format to not use any hotlist or other foreground color.

**Comment by pikajude** [comment]
So we can either set the foreground color of the selected buffer, or use colors per level, but not both?

**Comment by flashcode** [comment]
You can, by using a condition in the format, for example to display current buffer name in lightgreen:

    /set buflist.format.buffer "${format_number}${indent}${format_nick_prefix}${if:${current_buffer}?${color:lightgreen}:${color_hotlist}}${name}"

Note: this works only with version 1.9-dev (not 1.8), because `${current_buffer}` has been added in 1.9-dev.
