### ISSUE TITLE
irssi-like suspend/resume on SIGSTOP/SIGCONT and ctrl-z/fg

### ISSUE THREAD

**Issue by specing** [weechat/weechat#985]
Currently weechat does not suspend on CTRL-Z and upon resuming (after SIGSTOP/SIGCONT) one has to manually issue /redraw.

Required info:
* WeeChat 1.4 [compiled on May  2 2017 15:23:02]
* Gentoo
* Steps to reproduce:
   SIGSTOP followed by fg (time passed does not matter) results in a misrendered screen (/redraw has to be issued)

  CTRL-Z while weechat is running has no effect

* Scripts loaded: Matrix (few days old from their repo).

**Comment by flashcode** [comment]
I just checked, sending SIGTSTP (which is better than SIGSTOP because it can be handled by the application) will stop the process. So WeeChat will not reply to IRC servers on ping, therefore you can be disconnected (if you stay too long time outside WeeChat in the terminal).
Irssi has the same behavior, so you can be disconnected as well.

As a workaround, you can already bind yourself a key, for example on ctrl-Z:

    /key bind ctrl-Z /eval /exec kill -TSTP ${info:pid}

Just issueing `fg` after that should refresh WeeChat properly.

I can still add a default way to do that (and a clean refresh on SIGCONT signal), but anyway I'm not sure it's a good idea to stop WeeChat process like that.

**Comment by specing** [comment]
>  therefore you can be disconnected
That is intended

Pressin ctrl-z after that /key bind .... line results in help for kill being printed.

**Comment by flashcode** [comment]
Are you using at least WeeChat 1.7?
The info "pid" has been added in 1.7 (1.7.1 or 1.8 is recommended though).

**Comment by specing** [comment]
WeeChat 1.4 apparently
